### ISSUE TITLE
rootfs script failing for Ubuntu cross arm Dockerfile

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#1067]
Dockerfile: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/ubuntu/22.04/cross/arm/Dockerfile

```
 > [builder 3/3] RUN /scripts/eng/common/cross/build-rootfs.sh arm jammy lldb14 --skipunmount:
93.57 I: Extracting procps...
93.59 I: Extracting sed...
93.60 I: Extracting sensible-utils...
93.60 I: Extracting sysvinit-utils...
93.61 I: Extracting tar...
93.62 I: Extracting usrmerge...
93.62 I: Extracting util-linux...
93.65 I: Extracting zlib1g...
93.69 W: Failure trying to run: chroot "/crossrootfs/arm" /bin/true
93.69 W: See /crossrootfs/arm/debootstrap/debootstrap.log for details
```

[Failing build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2456222&view=results) (internal link)

This is a regression from https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1065. But it's strange because it was passing in the PR build with those changes. But it's not working on the internal build.

cc @jkoritzinsky

**Comment by jkoritzinsky** [comment]
I have no idea why this would not fail in PR but would immediately start failing in CI.

**Comment by lbussell** [comment]
[Triage] @jkoritzinsky can you investigate this?

**Comment by mthalman** [comment]
The fix in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1105 isn't working.
