### ISSUE TITLE
Debian 8 images have obsolete package feed configured

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-buildtools-prereqs-docker#107]
See https://lists.debian.org/debian-devel-announce/2019/03/msg00006.html

The base Debian images were updated earlier today via https://github.com/debuerreotype/docker-debian-artifacts/issues/66 but the 8.2 tag which is used here is no longer a supported tag.  Our options are to produce a debian:jessie(8.11) image or to stop producing a debian:8 image and force usage to the debian:9 image.

**Comment by wli3** [comment]
@MichaelSimons this also affected CLI repo's check in https://dev.azure.com/dnceng/public/_build/results?buildId=134793

Is there a jessie 8.11 docker image?

**Comment by wli3** [comment]
FYI @dotnet/dotnet-cli

**Comment by MichaelSimons** [comment]
@wli3 - There are now debian:jessie based images.

mcr.microsoft.com/dotnet-buildtools/prereqs:debian-jessie-coredeps-58e4974-20190328133153
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-jessie-58e4974-20190328133153
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-jessie-debpkg-58e4974-20190328133153
mcr.microsoft.com/dotnet-buildtools/prereqs:debian-jessie-corert-58e4974-20190328133153
