### ISSUE TITLE
CentOS Stream 8 build failing with appstream repo error

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#1085]
The build is failing with the error below when attempting to build this Dockerfile: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/centos/stream8/amd64/Dockerfile

```
 > [2/3] RUN dnf install --setopt tsflags=nodocs --refresh -y         dnf-plugins-core     &&     dnf config-manager --set-enabled powertools     &&     dnf module install --setopt tsflags=nodocs -y nodejs:20/common &&     dnf install -y epel-release &&     dnf install --setopt tsflags=nodocs -y         "perl(Time::HiRes)"         autoconf         automake         clang         cmake         curl-devel         doxygen         elfutils         file         findutils         gcc         gdb         git         glibc-langpack-en         hostname         jq         krb5-devel         libatomic         libcurl-devel         libedit-devel         libicu-devel         libidn2-devel         libnghttp2-devel         libtool         libuuid-devel         libunwind         libxml2-devel         lld         lldb-devel         llvm         lttng-ust-devel         lzma         make         ncurses-devel         numactl-devel         openssl-devel         procps-ng         python3         python3-devel         readline-devel         sudo         swig         tar         wget         which         xz         zlib-devel     &&     dnf clean all:
0.799 CentOS Stream 8 - AppStream                     154  B/s |  38  B     00:00    
0.806 Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

[Example build](https://dev.azure.com/dnceng/internal/_build/results?buildId=2465213&view=logs&j=d1148b52-1507-508d-9dbd-96abb13f0748&t=9fedf1e0-fa86-5312-7528-d0353326aa37) (internal link)

**Comment by mthalman** [comment]
This error occurs just by running `dnf update`. @omajid - are you aware of any issue going on with the repositories?

**Comment by omajid** [comment]
CentOS Stream 8 reached its end of life a few days ago. And they did a hard notification of this EOL by disabling all repos.

We need to turn off CentoS Stream 8 legs or migrate to an alternative. Alternatively, if we really want to continue to use CentOS Stream 8, we need to update the repo configuration to point to the historical archive: https://vault.centos.org/8-stream/

**Comment by MichaelSimons** [comment]
Related to https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/973 - we should drop these images.  Source Build CI has migrated off of them
