### ISSUE TITLE
Building rootfs fails for ubuntu-22.04-cross-riscv64

### ISSUE THREAD

**Issue by sbomer** [dotnet/dotnet-buildtools-prereqs-docker#1088]
This is failing consistently with:
```
 > [builder 3/3] RUN /scripts/eng/common/cross/build-rootfs.sh riscv64 sid --skipunmount:
13.14 I: Retrieving usrmerge 39
13.14 I: Validating usrmerge 39
13.16 I: Retrieving util-linux 2.40.1-8.1
13.17 I: Validating util-linux 2.40.1-8.1
13.19 I: Retrieving zlib1g 1:1.3.dfsg+really1.3.1-1
13.21 I: Validating zlib1g 1:1.3.dfsg+really1.3.1-1
13.22 I: Chosen extractor for .deb packages: dpkg-deb
13.25 I: Extracting apt...
13.34 I: Extracting base-files...
13.35 E: Tried to extract package, but file already exists. Exit...
```

Not sure when it started failing, but it happens for example in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1087 and https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1083.

@am11, any idea what might be causing this?

**Comment by am11** [comment]
debootstrap version is old.
* Solution 1: switch host layer to CBL-Mariner/AzL and use 24.04 rootfs for riscv64 (now that it's a stable arch since 24.04; no longer an experimental arch)
* Solution 2: switch host layer to Ubuntu 22.04 and keep using Debian sid
* Solution 3: add the following three lines in crossdeps layer:
	```sh
	git clone --depth 1 https://git.launchpad.net/ubuntu/+source/debootstrap /debootstrap
	chmod a+x /debootstrap/debootstrap
	ln -s /debootstrap/debootstrap -t /usr/local/bin
	```

I have tested 2 and 3 and it works. The best would be 1 (with clang 18 if possible).
3 is the fastest, stop-gap solution.

**Comment by am11** [comment]
For solution 1, we can start by adding sources.list.nobel at https://github.com/dotnet/arcade/tree/main/eng/common/cross/riscv64, followed by the work in this repo. If you are already on it, I can give moral support and help testing. 😄

**Comment by am11** [comment]
Solution 1 can use solution 3 `git clone --depth 1 https://git.launchpad.net/ubuntu/+source/debootstrap /debootstrap` etc. until debootstrap is update in Azure Linux packages?

**Comment by richlander** [comment]
I am having a related problem in #1096.

I see this.

```bash
#5 [builder 1/3] FROM mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-22.04-crossdeps-local
#5 CACHED

#6 [builder 3/3] RUN /scripts/eng/common/cross/build-rootfs.sh riscv64 sid --skipunmount
#6 0.249 running debootstrap --variant=minbase --keyring /usr/share/keyrings/debian-archive-keyring.gpg --include=debian-archive-keyring --force-check-gpg --arch riscv64 sid /crossrootfs/riscv64 http://ports.ubuntu.com/
#6 0.304 I: Retrieving InRelease 
#6 0.679 I: Retrieving Release 
#6 1.052 E: Failed getting release file http://ports.ubuntu.com/dists/sid/Release
#6 ERROR: executor failed running [/bin/sh -c /scripts/eng/common/cross/build-rootfs.sh riscv64 sid --skipunmount]: exit code: 1
------
```

It is indeed true that http://ports.ubuntu.com/dists/sid/Release 404s. Lots of other releases are at the parent directory: http://ports.ubuntu.com/dists/.

Why do we use `sid`? Why note use the matching distro version?

**Comment by am11** [comment]
We use sid because risc-v is a new emerging architecture. Now that Ubuntu Nobel is released in April with first class risc-v support, we should switch to Nobel instead. Replace `sid` with `nobel`. @sbomer was going to move it to Azure Linux at the same time.

**Comment by am11** [comment]
@sbomer sid-> nobel for linux and alpineedge -> alpine3.20 for linux-musl.
