### ISSUE TITLE
`libmsquic` is missing for Ubuntu 24.04

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-buildtools-prereqs-docker#1097]
I am building Ubuntu 24.04 Helix images in #1096. `libmsquic` is not available. Presumably we should either build from source or get the MSQuic team to publish Ubuntu 24.04 packages.

@wfurt

**Comment by wfurt** [comment]
we should push this to msquic. cc @nibanks @CarnaViire 
In the mean time, we should fetch from closes version. It is identical binary anyway.

**Comment by richlander** [comment]
I tried that, but failed. Maybe I misunderstood the error. Do you have an example where that is done with APT?

**Comment by wfurt** [comment]
We used to do that in Ubuntu 18 .... but it is gone now

This is simples way IMHO
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/commit/87aa25266dc666f64420f463c7b031d14aaafc35

We can possibly add the repo to make updates easier.

**Comment by richlander** [comment]
That didn't work since it appears that `libmsquic` is Y2038 incompatible. Let's wait for the msquic team to produce a binary that is known good on Ubuntu 24.04 (and Debian 13).

Context: https://github.com/dotnet/core/discussions/9285

**Comment by jkoritzinsky** [comment]
Fixed by https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1156
