### ISSUE TITLE
Re-enable Arm32 Debian images

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#1132]
Some Dockerfiles were disabled by https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/927. These need to be fixed and re-enabled.

**Comment by lbussell** [comment]
[Triage] Debian 10 is EOL so these images should not be re-enabled. If needed by product teams, they can be re-added for later versions of Debian.

**Comment by lbussell** [comment]
[Triage] Debian 11 images were also disabled with https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/927. It seems these images are still being used. @wfurt, we should either fix this image or update it to a new one.

@ilyas1974, FYI, the Matrix of Truth is flagging Debian 11 as EOL at the end of the month, but it is entering long-term support for another 2 years until 2026 (see https://wiki.debian.org/LTS).

**Comment by mthalman** [comment]
Confirmed that this is still an issue in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1258.

@wfurt - Can you take a look?

**Comment by mthalman** [comment]
> Confirmed that this is still an issue in [#1258](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1258).
> 
> [@wfurt](https://github.com/wfurt) - Can you take a look?

Never mind. This Dockerfile needs to be removed anyway as part of https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/1260.

Since the Raspbian Dockerfile has also since been removed, that means there is no work to do here.
