### ISSUE TITLE
Use debootstrap 1.0.137 for cross riscv64 Dockerfile

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#1146]
When debootstrap 1.0.137 is available from Debian's repository feed, this installation should be updated:

https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/b5523942e8a2cf245f4e39d000bd09b53714d52f/src/azurelinux/3.0/net9.0/cross/riscv64/Dockerfile#L6-L14

It should follow the same installation pattern that previously existed prior to the changes in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1144. See https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1144#issuecomment-2245260620 for more info.

**Comment by lbussell** [comment]
[Triage] It appears that debootstrap version 1.0.137 is available now, so this work can be completed any time now.
