### ISSUE TITLE
Define owner(s) for each Dockerfile

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-buildtools-prereqs-docker#1148]
There is a need to identify the owner(s) of the build tools Dockerfiles.  The owner will be contacted/assigned issues in the following scenarios:

1. When there is a build break.
1. When there is a fixable vulnerability that requires a code change (e.g. a simple rebuild will not address).

**Considerations:**

1. Where to define the owner?  CODEOWNERS feels like a natural mechanism.  The manifest.json could be modified to support this as well.
1. Are teams allowed?  Issues cannot be assigned to an issue.  You could assign issues to all members of a team but that doesn't provide a great dev UX.
1.  Validation should be created to ensure all Dockerfiles have an owner defined.

Related to https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/972

**Comment by ellahathaway** [comment]
@MichaelSimons - do both scenarios occur in runs of the following pipelines? https://dev.azure.com/dnceng/internal/_build?definitionScope=%5Cdotnet%5Cdotnet-buildtools-prereqs-docker

I would imagine that scenario 1 does (I found a few closed issues to support this assumption), but I'm not sure if scenario 2 does. I'm assuming that if there's is a vulnerability that requires a code change that it would appear in the component detection step, but I wanted to double check.

**Comment by MichaelSimons** [comment]
> do both scenarios occur in runs of the following pipelines?

No the second scenario is the goal (see https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/1150).  This isn't feasible yet until the EOL Annotations feature lands as there is too much noise in the vulnerability reports.

**Comment by ellahathaway** [comment]
> Are teams allowed? Issues cannot be assigned to an issue. You could assign issues to all members of a team but that doesn't provide a great dev UX.

See https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1153#discussion_r1700887843

The policy will be to ping a team on an issue over an individual.

Assigning individuals can get tricky if someone is OOF or non-responsive. In that instance, we'd have to track down the team they belong to and ping them anyways.
