### ISSUE TITLE
[Ubuntu24.04] msquic dependency issues

### ISSUE THREAD

**Issue by liveans** [dotnet/dotnet-buildtools-prereqs-docker#1157]
msquic 2.4.1 package has 2 different dependency issues on Ubuntu24.04.

1-) It depends on `libxdp1 libnl-3-dev libnl-route-3-dev` but they are not getting installed. (All architectures)
2-) It depends on libssl3 but it's not available for armhf, and should be dependent on libssl3t64.

Change these conditions in Ubuntu24.04 helix images once issues are fixed.

/cc @ManickaP

**Comment by wfurt** [comment]
it should _NOT_ depend on `-dev` packages.

**Comment by ManickaP** [comment]
These 3 were missing:
```
libxdp.so.1 => not found
libbpf.so.1 => not found
libnl-3.so.200 => not found
libnl-route-3.so.200 => not found
```
