### ISSUE TITLE
Remove the install-cross-build-prereqs functionality

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-buildtools-prereqs-docker#1159]
Is the following install-cross-build-prereqs functionality still needed after https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1065?

https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/eng/pipelines/steps/install-cross-build-prereqs.yml
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/ubuntu/build-scripts/install-cross-build-prereqs.sh

cc @jkoritzinsky, @mthalman

**Comment by mthalman** [comment]
Yes. The host still needs to be configured appropriately. A recent example of running into this is https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1106.

**Comment by MichaelSimons** [comment]
Thanks for the pointed, that made things "click" for me.  The script really is not located in a good location.
