### ISSUE TITLE
CMake generate step failing in `Linux_amd64 src-azurelinux-3.0-net9.0-crossdeps-graph` jobs

### ISSUE THREAD

**Issue by ellahathaway** [dotnet/dotnet-buildtools-prereqs-docker#1160]
Several public PR builds are failing with the following error:

```
#8 5.342 CMake Error at /llvm-project.src/libcxx/cmake/Modules/HandleLibCXXABI.cmake:59 (add_library):
#8 5.342   No SOURCES given to target: libcxx-abi-headers-generate-private-headers
```

Below are three builds which have experienced the error:

- https://dev.azure.com/dnceng-public/public/_build/results?buildId=766292&view=logs&j=9451fe7a-3b19-5e32-5ae2-ab8409ac889d&t=8b49f318-ee4b-51db-c9b2-6c2579fdf8cb
- https://dev.azure.com/dnceng-public/public/_build/results?buildId=766733&view=logs&j=9451fe7a-3b19-5e32-5ae2-ab8409ac889d&t=8b49f318-ee4b-51db-c9b2-6c2579fdf8cb
- https://dev.azure.com/dnceng-public/public/_build/results?buildId=767687&view=logs&j=9451fe7a-3b19-5e32-5ae2-ab8409ac889d&t=8b49f318-ee4b-51db-c9b2-6c2579fdf8cb

I first noticed this in checks for [this PR](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1153), and the errors are unrelated to the changes in that PR.

**Comment by mthalman** [comment]
This is the affected command:

https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/7146e2abbc287afa8bc383c116256c8543ad004d/src/azurelinux/3.0/net9.0/cross/riscv64-alpine/Dockerfile#L8-L31

@am11 - Can you investigate?

**Comment by am11** [comment]
@mthalman that file is for Linux-musl-riscv64. We don’t even have a CI leg for it. These errors are occurring in other legs like linux arm.

**Comment by mthalman** [comment]
> that file is for Linux-musl-riscv64. We don’t even have a CI leg for it.

Are you implying that there's no need for this Dockerfile and it can be removed?

> These errors are occurring in other legs like linux arm.

Not sure what you mean by this. Can you provide a relevant link?

**Comment by am11** [comment]
OK, I was on the phone and was reading it wrong. So it has just started to fail? It wasn't failing in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1098 and many builds since, right?

**Comment by mthalman** [comment]
It just started failing recently.

**Comment by am11** [comment]
> Are you implying that there's no need for this Dockerfile and it can be removed?

Even if it's not used in runtime today, we want to keep it to test the builds. I use it in github actions and others too. I will eventually add it to community pipeline (in dotnet/runtime) as well, but haven't gotten enough cycle to go about it.

**Comment by am11** [comment]
PR is up https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1162.
