### ISSUE TITLE
CODEOWNERS file doesn't include docker review team by default

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#1163]
Example PR: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1162

I would expect that `@dotnet/dotnet-docker-reviewers` be added as a reviewer to _all_ PRs in this repo.

/cc @ellahathaway

**Comment by ellahathaway** [comment]
> I would expect that `@dotnet/dotnet-docker-reviewers` be added as a reviewer to all PRs in this repo.

The `*` path means that the owner applies to all files in the repo, so I would expect that `@dotnet/dotnet-docker-reviewers` be added as a reviewer to all PRs as well. I'll read through github's codeowner documentation again to see what's going on.

**Comment by ellahathaway** [comment]
So apparently the CODEOWNER lines do not compound but rather they exclude. Essentially, with each line you add to the file, if it conflicts with an owner assignment on a previous line, the previous line will get overridden. This is a bit frustrating to learn. In fact, it's only mentioned in the example provided in [github's CODEOWNERs documentation](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners):

```
# These owners will be the default owners for everything in
# the repo. Unless a later match takes precedence,
# @global-owner1 and @global-owner2 will be requested for
# review when someone opens a pull request.
*       @global-owner1 @global-owner2

# Order is important; the last matching pattern takes the most
# precedence. When someone opens a pull request that only
# modifies JS files, only @js-owner and not the global
# owner(s) will be requested for a review.
*.js    @js-owner #This is an inline comment.
```
