### ISSUE TITLE
Don't pin msquic version on Alpine

### ISSUE THREAD

**Issue by liveans** [dotnet/dotnet-buildtools-prereqs-docker#1182]
Currently we're pinning msquic version in Alpine helix images as you can see below:

https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/38e30ba6767216fb0d6ab3ef2d7be6aa95e2266d/src/alpine/3.20/helix/Dockerfile#L18

Ideal solution is getting latest release from msquic releases page.
We can do this as explained in here: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1156#discussion_r1705458486

**Comment by lbussell** [comment]
[Triage] Related: #1171
