### ISSUE TITLE
Rebuild images on a regular basis

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#1224]
In order to keep the images fresh and up-to-date by default, there should be a policy or automation to rebuild images on a regular basis. This will ensure that latest package updates are retrieved when configured to do so. This will help to reduce the need to manually respond to any vulnerability alerts that might pop up.

Proposal: setup the pipeline to run on the 15th of every month, configured to run with caching disabled. That will be the day after the latest possible Patch Tuesday. It'd probably be ok to exclude Windows images as these will automatically be rebuilt on Patch Tuesday.

**Comment by lbussell** [comment]
[Triage] Related: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/988

In order to make best use of this proposed re-building schedule, we should make sure https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/1228 is done first.
