### ISSUE TITLE
Raspbian Dockerfiles should include a package upgrade by default

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-buildtools-prereqs-docker#1238]

**Comment by MichaelSimons** [comment]
These Dockerfiles are being removed with https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1241.

**Comment by mthalman** [comment]
This either shouldn't be closed yet or feedback should be provided in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1083 to make this change.

**Comment by MichaelSimons** [comment]
> This either shouldn't be closed yet or feedback should be provided in [#1083](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/1083) to make this change.

Already closed.

**Comment by mthalman** [comment]
No, I'm saying it _shouldn't_ be closed yet because there is pending Raspbian changes coming in.
