### ISSUE TITLE
Separate cross-build images into their own images

### ISSUE THREAD

**Issue by jashook** [dotnet/dotnet-buildtools-prereqs-docker#16]
The current architecture will force the crossbuild image to include each rootfs. For multi-arch builds it is nice to only target one cross image. That being said, it would be nice to have arch specific images for space saving purposes. For example, building coreclr-arm does not require the x86,  and arm64 rootfs.

**Comment by sdmaclea** [comment]
When we do this can we also try shrinking the images as suggested here https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/23#issuecomment-373534178

It probably means adding this before the tar command
```
    echo "Cleaning apt files"
    docker exec $buildRootFSContainer \
        rm -rf /rootfs/$arch/var/cache/apt/archives/* /rootfs/$arch/var/lib/apt/lists/*

```

I think errors here can be ignored.

**Comment by sdmaclea** [comment]
https://github.com/dotnet/coreclr/issues/16513

**Comment by jashook** [comment]
This has been mostly addressed.
