### ISSUE TITLE
Define Helix images for Alpine 3.10

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#182]

**Comment by MattGal** [comment]
This is done and merged, not sure why the updated image is not in the list yet though?

**Comment by mthalman** [comment]
Build isn't done yet.

**Comment by mthalman** [comment]
Build is done now: https://github.com/dotnet/versions/commit/e1d35818b0b99bd8a26e8ec98e96a3c2d471fd78
