### ISSUE TITLE
Need equivalent RHEL 8 of rhel-7-rpmpkg-e1b4a89-20175311035359

### ISSUE THREAD

**Issue by wli3** [dotnet/dotnet-buildtools-prereqs-docker#194]
SDK need to update CI legs to the latest RHEL 8. We hope to get an equivalent RHEL 8 image to  rhel-7-rpmpkg-e1b4a89-20175311035359 that has tool chain for rpm packages.

**Comment by MichaelSimons** [comment]
@wli3 - is it possible to utilize a CentOS image for your work?  There are blocking issues that prevent us from producing RHEL images within this repo.

**Comment by dagood** [comment]
Related, issue tracking adding a centos RPM build image: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/92.

**Comment by wli3** [comment]
We do have CentOS, I think we will just skip RHEL 8 in the meantime @leecow

**Comment by leecow** [comment]
CentOS 8 should be a reliable proxy.

**Comment by MichaelSimons** [comment]
Closing this as a replacement CentOS image is covered under https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/92.
