### ISSUE TITLE
Can this repo be more "self serve"?

### ISSUE THREAD

**Issue by wli3** [dotnet/dotnet-buildtools-prereqs-docker#195]
Per this comment https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/92#issuecomment-468490398

If the product team is responsible for the special docker image, I hope we can cut down most of the back and forth. The following is the flow I am currently in to updating docker files (to use the latest Linux distros)

1. Change the docker file inside SDK
2. Send WIP PR to test the change actually works
3. Send PR to https://github.com/dotnet/dotnet-buildtools-prereqs-docker
4. Wait for approval and get a build
5. Use the image in SDK repos

If there is something wrong I need to start from 3-5 again. The whole process is lengthy. I am wondering if the process could be more self service like cutting the review so there is no wait on a human in the process since in the end as long as it can build, it is enough.

**Comment by MichaelSimons** [comment]
Is there no way you can build and test the image locally before even sending a PR to this repo?  The whole workflow of relying on this repo's build to produce the image seems like a long pole you should try to avoid while developing the Dockerfiles.

What is your proposal on when the Dockerfile should be reviewed?  To date, I am not comfortable in eliminating this step as numerous improvements have been made as a result of them.

**Comment by wli3** [comment]
_test the image locally_ -- that would still need 2 PRs to finish one dockerfile update. And we are blocked on an other person (totally 2 in this case) to review for a rather simple change.

_numerous improvements_ -- For almost all SDK's docker files, they are just a lot of apt-get etc installs. Maybe skip review if it is on some folders? And could we automate some of the steps like the manifest authoring to avoid human intervention?

After @leecow yesterday's meeting, we would need to keep up with distro changes much more frequently. With current process, I don't think we can keep up easily. cc @livarcocc

**Comment by MichaelSimons** [comment]
> _test the image locally_ -- that would still need 2 PRs to finish one dockerfile update. And we are blocked on an other person (totally 2 in this case) to review for a rather simple change.

Testing locally would eliminate the need to cycle on 3-5.  It would dramatically speed up your development cycle.

> _numerous improvements_ -- For almost all SDK's docker files, they are just a lot of apt-get etc installs. Maybe skip review if it is on some folders? And could we automate some of the steps like the manifest authoring to avoid human intervention?

Can you explain what you mean by _manifest authoring_ here?

In general, when we need to onboard a new distro version and the Dockerfiles are virtually identical between versions (e.g alpine 3.9 to alpine 3.10) , I think it is reasonable to make a PR, wait for CI to be green, and then merge with a comment indicating that the changes are identical to the previous version and that you are  merging to unblock consumption.  The reviewers can retro-actively review as appropriate.  I do not feel this is the appropriate process however when there are significant changes or a completely new Dockerfile is being added.

**Comment by MichaelSimons** [comment]
@wli3 - Does my last response seem reasonable?

**Comment by wli3** [comment]
Yes, sorry for the delay, the solution is great.
