### ISSUE TITLE
Ask for OpenSUSE 15 image

### ISSUE THREAD

**Issue by wli3** [dotnet/dotnet-buildtools-prereqs-docker#196]
This is our old OpenSUSE image https://github.com/dotnet/core-sdk/blob/7464d9bca4a2f25d1f832f9ef51ed288d4b0201e/eng/docker/opensuse.42.3/Dockerfile

I tried to create a docker file myself, however I cannot do it easily. It fails on `RUN useradd -m code_executor -u ${USER_ID} -g wheel`, for cannot finding the `wheel` group. And if I remove this line, later it cannot run Arcade to install SDK.

I am wondering if you can help me create a replacement for that image?

**Comment by MichaelSimons** [comment]
@wli3 - It would be helpful if you would include the Dockerfile you have created.  That aside, from doing a simple web search along with a quick test, the `wheel` group is not a predefined group in OpenSUSE 15.  You will either need to create the group or consider using an existing group.

**Comment by MichaelSimons** [comment]
@wli3, The product teams are responsible for the authoring of the Dockerfiles/images they need.   We provide the infra to produce the images and can provide assistance in authoring when needed.

**Comment by wli3** [comment]
As the email we sent out earlier this we. My team decided SDK will piggyback the docker image after the runtime team. We will wait for their docker image to be published

**Comment by wli3** [comment]
Thanks!
