### ISSUE TITLE
Curl CLI issues in ubuntu 18.04 images

### ISSUE THREAD

**Issue by eiriktsarpalis** [dotnet/dotnet-buildtools-prereqs-docker#198]
I'm trying to build corefx using the `prereqs:ubuntu-18.04-*` images, however they're all invariably failing with curl errors:
```
$ docker run -it mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-3e800f1-201908 
14211606 curl
curl: error while loading shared libraries: libcurl.so.4: cannot open shared object file: No such file or directory
```

**Comment by wfurt** [comment]
I think this is partially on purpose. We (CurlHandler) depends traditionally on libcurl3 and that is mutually exclusive with libcurl4. Master/3.0 is fixed and it should work but that may break older .Net releases if we care.

**Comment by eiriktsarpalis** [comment]
I assumed so as well, wondering if we could install a compatible curl command in the image.

**Comment by MichaelSimons** [comment]
@eiriktsarpalis, what is the scenario you want curl for?  Would wget satisfy the use case?  @wfurt, do you have an opinion on this?

**Comment by wfurt** [comment]
As I was thinking about this, older dotnet branches would use older images, right? So it may be ok to move to newer libcurl as we now (finally!) support openssl1.1. In the past that was the biggest blocker.

**Comment by eiriktsarpalis** [comment]
> what is the scenario you want curl for?

It's used by the corefx build script, for example [here](https://github.com/dotnet/corefx/blob/425538f6717ade11afa28b9ee8ca0522c3c90ece/eng/common/tools.sh#L232). It seems to have wget fallback logic which doesn't work in this case.

**Comment by MichaelSimons** [comment]
@eiriktsarpalis - in regard to 

> It's used by the corefx build script, for example here. It seems to have wget fallback logic which doesn't work in this case.

It sounds like this a bug in the script?  If so, have you checked to see if an issue exists or logged a new one?

I have no objection to updating libcurl, I defer to @wfurt to make that decision.

**Comment by eiriktsarpalis** [comment]
> It sounds like this a bug in the script?

I wouldn't think so, it's using a fairly standard way of checking whether curl is available.

**Comment by MichaelSimons** [comment]
@eiriktsarpalis - feel free to make a PR for add curl to the Dockerfiles.

**Comment by wfurt** [comment]
I'm wondering if we should close this. .NET no longer needs `curl` or `libcurl` so this should not be a problem.

**Comment by mthalman** [comment]
> I'm wondering if we should close this. .NET no longer needs `curl` or `libcurl` so this should not be a problem.

And the fact that this issue is over 2 years old and things have seemingly been going fine. I'll close this. Feel free to create a PR to correct things if needed.
