### ISSUE TITLE
What caused /usr/bin/sh setlocale: LC_ALL: cannot change locale (en_US.UTF-8) on Linux?

### ISSUE THREAD

**Issue by wli3** [dotnet/dotnet-buildtools-prereqs-docker#199]
This is a question. I think you might have a better answer. Do you know what caused the error `/usr/bin/sh setlocale: LC_ALL: cannot change locale (en_US.UTF-8) ` on Linux?
 https://dev.azure.com/dnceng/public/_build/results?buildId=386114&view=logs

It happens when the docker image does not have the correct locale. However I don't know where in the stack this error happens, and what is the solution since so far I cannot make SDK work on Fedora 30

**Comment by dagood** [comment]
Related PR: https://github.com/dotnet/core-sdk/pull/5186#discussion_r334204550

@crummel, you mentioned fixing something like this in https://github.com/dotnet/source-build/pull/1014, but I don't see what it was, do you have some more info on this? Is there something that could be applied to dotnet-buildtools-prereqs-docker to help everyone?

**Comment by wli3** [comment]
I am having the same issue on Debian stretch https://github.com/dotnet/core-sdk/pulls

@tannergooding I am trying my luck. Do you know who may know this issue?

**Comment by crummel** [comment]
We used an extremely brute-force approach: https://github.com/dotnet/source-build/blob/1bcf041037537b46508328fa916a77bc9e20855f/build.sh#L29.  It's definitely not a good fix, but I think it could be temporarily applied anywhere.

**Comment by wfurt** [comment]
Assuming given language is available it tricky. I've see LANG=C in past to force Posix  (and only available on Alpine). But that could break .NET prior to 3.0 as it would assume case-sensitive strings even if asked explicitly for case-insensitive comparison)

For now it may be worth of updating documentation to get expected locale prior of building.

**Comment by wli3** [comment]
So this is a lacking locale issue? And the right fix should be apt-get install the missing locale?

**Comment by MichaelSimons** [comment]
In the scope of Fedora 30, @Omajid provided some [additional context here](https://github.com/dotnet/source-build/issues/1324#issuecomment-548885319) with some suggested fixes

> There's two fixes for this, as far as I can tell:
> 
> Use a C locale. C/C.UTF-8/POSIX work out of the box
> Install the language pack for the non-C locale. That's what glibc-langpack-en does.

**Comment by MichaelSimons** [comment]
@wli3 - Have your questions been sufficiently answered?  Can this issue be closed?

**Comment by wli3** [comment]
Thanks
