### ISSUE TITLE
ubuntu-16.04 cross image no longer builds

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-buildtools-prereqs-docker#204]
ubuntu-16.04 cross image no longer builds fails to build while running build-rootfs.sh.  see https://dev.azure.com/dnceng/public/_build/results?buildId=417916&view=logs&j=7e9b14cd-47a0-562c-e7e8-7f0ef272e133

```
ERROR: unsatisfiable constraints:
  so:libpython3.7m.so.1.0 (missing):
```

See discussion at https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/203#issuecomment-550496350

cc @janvorli, @mikem8361, @jkoritzinsky

**Comment by jkoritzinsky** [comment]
Fixing this is required to generate Ubuntu 16.04 Docker images with CMake 3.15.5 (the minimum requirement for the consolidated runtime repository)

**Comment by jkoritzinsky** [comment]
The current images do have CMake 3.15.4 so this isn't blocking (the fix in CMake 3.15.5 that we're depending on is Windows-only).

**Comment by janvorli** [comment]
The fix in arcade has been merged in today. I've verified that I can build the ubuntu-16.04 arm64 Alpine cross image locally now.

**Comment by MichaelSimons** [comment]
Thanks @janvorli.

@mthalman - Can you trigger a build to pick up these changes?

**Comment by mthalman** [comment]
Images are built and published.  Closing.
