### ISSUE TITLE
Define Helix image for Alpine 3.11

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#224]
Define a Helix image for Alpine 3.11 which has been recently [released](https://alpinelinux.org/posts/Alpine-3.11.0-released.html).

**Comment by MattGal** [comment]
PR should be ready to merge, will do so once https://dev.azure.com/dnceng/public/_build/results?buildId=474742&view=logs&j=4ea1c03d-29ac-501e-0c0f-6cb4dee156a2&t=7b24a75c-4dba-5377-8e9c-500c7ab561c8 is green .

**Comment by MattGal** [comment]
Moved to rollout; will close once an image gets published and I can run a simple Helix job through it.

**Comment by MattGal** [comment]
I've tested mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.11-helix-08e8e40-20200107182408 successfully and made a PR to adopt it in the runtime repo: https://github.com/dotnet/runtime/pull/1373 .  Closing.
