### ISSUE TITLE
Move published images from MCR to ACR configured with public anonymous access

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-buildtools-prereqs-docker#228]
The dotnet-buildtools-prereqs images aren't a good fit to be hosted on MCR.

1. We don't want a presence on Docker Hub.  The primary reason for this is we don't want end users to discover this repo and think it is something they should be using.  We don't want to cause end user confusion and detract users from discovering the official .NET Core repos.  These images are for the purposes of building the product itself.
2. MCR has a higher bar than what is necessary for this repo.  For example the images hosted on MCR are scanned for vulnerabilities on a regular basis and there are expectations around how quickly the vulnerabilities are addressed.  This particular issue is causing a lot of contention as of right now.
3. When these images were originally published to MCR it was the only viable option.  One of the primary requirements was that they were publicly accessible so that anyone contributing to .NET could make use of them.  Keeping them on Docker Hub was not an option and ACR didn't support anonymous access.

[ACR now supports anonymous access](https://feedback.azure.com/forums/903958-azure-container-registry/suggestions/32517127-enable-anonymous-access-to-registries) albeit it is still in preview.  This would be a much better fit for the hosting the dotnet-buildtools-prereqs images.

**Comment by mthalman** [comment]
Based on the feedback from the MAR team, the plan is to continue hosting these in MAR since these are still available for public development use.
