### ISSUE TITLE
Automatically rebuild images anytime their base image is updated

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-buildtools-prereqs-docker#229]
The dotnet-buildtools-prereqs images are built only when changes are made to the Dockerfiles or when a build is manually triggered.  This is not good as the product builds are not running with the latest OS and package patches.  The images should automatically get rebuilt anytime the base image is changed.  This change would align the image behavior with the build VMs in that the build VMs are updated to get the latest patches.

This can easily be accomplished by adding an entry in this [subscription file](https://github.com/dotnet/docker-tools/blob/master/eng/check-base-image-subscriptions.json).

In order to have the new images picked up by the product teams, changes are needed to the tagging scheme to no longer include a build timestamp.

**Comment by mthalman** [comment]
This is implemented by https://github.com/dotnet/docker-tools/pull/1075.
