### ISSUE TITLE
Update dotnet/versions with missing build-info

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/dotnet-buildtools-prereqs-docker#238]
Because of [this issue](https://github.com/dotnet/docker-tools/pull/389), the dotnet/versions build-info was not updated with the recent images built from this repo.  The build-info should be updated to reflect the images produced as a result of merging the following PRs.

* https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/236
* https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/233

This is necessary because the build-info is the documented way the README instructs users on how to find the most recent images.

**Comment by mthalman** [comment]
Fixed by https://github.com/dotnet/versions/pull/554
