### ISSUE TITLE
Add Python 3 to images

### ISSUE THREAD

**Issue by CoffeeFlux** [dotnet/dotnet-buildtools-prereqs-docker#244]
Mono needs Python 3 for a bunch of our scripts. I attempted to enforce this in configure.ac, but it looks like the Linux images are all missing it (see https://github.com/dotnet/runtime/pull/2372).

**Comment by MichaelSimons** [comment]
@CoffeeFlux - Can you be explicit on which images need this?  

FYI - Typically this repo is self serving.  By that I mean the individual teams which need changes would make the changes and submit a PR.

**Comment by CoffeeFlux** [comment]
Cent 7 and Alpine. I can PR it then, wasn't sure what the standard workflow is - we just moved Mono into the runtime repo and I'm largely unfamiliar with the build system/infra.
