### ISSUE TITLE
CentOS 6 build is failing when attempting to install ICU

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#300]
The Dockerfile attempts to download and extract an ICU .tgz file here:
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/20b72af0c053424c6c5cd0a56981d25e75c7a314/src/centos/6/Dockerfile#L154

But it fails because that URL actually takes you to a webpage; it doesn't reference a .tgz file.

**Comment by crummel** [comment]
Without the original tgz it's hard to know but it almost looks like it might not have been doing anything - there's no `make` or `cp` from a `icu4c-57` directory that would be the standard for *nix.  Have we tried just removing that section?

**Comment by mthalman** [comment]
Here's a dump of the list of files that are being added by this layer:

```
./usr/local/sbin/gensprep
./usr/local/sbin/icupkg
./usr/local/sbin/genccode
./usr/local/sbin/gencmn
./usr/local/sbin/gennorm2
./usr/local/share/man/man1/uconv.1
./usr/local/share/man/man1/derb.1
./usr/local/share/man/man1/genbrk.1
./usr/local/share/man/man1/gendict.1
./usr/local/share/man/man1/gencnval.1
./usr/local/share/man/man1/makeconv.1
./usr/local/share/man/man1/gencfu.1
./usr/local/share/man/man1/pkgdata.1
./usr/local/share/man/man1/icu-config.1
./usr/local/share/man/man1/genrb.1
./usr/local/share/man/man8/gencmn.8
./usr/local/share/man/man8/gensprep.8
./usr/local/share/man/man8/genccode.8
./usr/local/share/man/man8/icupkg.8
./usr/local/share/icu
./usr/local/share/icu/57.1
./usr/local/share/icu/57.1/install-sh
./usr/local/share/icu/57.1/config
./usr/local/share/icu/57.1/config/mh-linux
./usr/local/share/icu/57.1/LICENSE
./usr/local/share/icu/57.1/mkinstalldirs
./usr/local/lib/libicuuc.so.57.1
./usr/local/lib/libiculx.so
./usr/local/lib/libicutest.so.57.1
./usr/local/lib/libicuio.so
./usr/local/lib/libicule.so
./usr/local/lib/libiculx.so.57.1
./usr/local/lib/libicui18n.so.57
./usr/local/lib/libicuuc.so.57
./usr/local/lib/libicutest.so.57
./usr/local/lib/libicutu.so.57
./usr/local/lib/libicudata.so.57
./usr/local/lib/libicule.so.57.1
./usr/local/lib/libicudata.so.57.1
./usr/local/lib/libicuio.so.57.1
./usr/local/lib/libiculx.so.57
./usr/local/lib/libicuio.so.57
./usr/local/lib/libicuuc.so
./usr/local/lib/pkgconfig/icu-i18n.pc
./usr/local/lib/pkgconfig/icu-io.pc
./usr/local/lib/pkgconfig/icu-le.pc
./usr/local/lib/pkgconfig/icu-lx.pc
./usr/local/lib/pkgconfig/icu-uc.pc
./usr/local/lib/libicutest.so
./usr/local/lib/libicule.so.57
./usr/local/lib/libicutu.so
./usr/local/lib/libicutu.so.57.1
./usr/local/lib/libicui18n.so
./usr/local/lib/libicui18n.so.57.1
./usr/local/lib/icu
./usr/local/lib/icu/Makefile.inc
./usr/local/lib/icu/pkgdata.inc
./usr/local/lib/icu/57.1
./usr/local/lib/icu/57.1/Makefile.inc
./usr/local/lib/icu/57.1/pkgdata.inc
./usr/local/lib/icu/current
./usr/local/lib/libicudata.so
./usr/local/lib/libcurl.la
./usr/local/lib/libcurl.so.4.4.0
./usr/local/include/layout
./usr/local/include/layout/playout.h
./usr/local/include/layout/LETypes.h
./usr/local/include/layout/LETableReference.h
./usr/local/include/layout/LEGlyphStorage.h
./usr/local/include/layout/LEFontInstance.h
./usr/local/include/layout/LayoutEngine.h
./usr/local/include/layout/loengine.h
./usr/local/include/layout/plruns.h
./usr/local/include/layout/LESwaps.h
./usr/local/include/layout/LEInsertionList.h
./usr/local/include/layout/ParagraphLayout.h
./usr/local/include/layout/RunArrays.h
./usr/local/include/layout/LEScripts.h
./usr/local/include/layout/LELanguages.h
./usr/local/include/layout/LEGlyphFilter.h
./usr/local/include/unicode
./usr/local/include/unicode/ucoleitr.h
./usr/local/include/unicode/caniter.h
./usr/local/include/unicode/coleitr.h
./usr/local/include/unicode/ulocdata.h
./usr/local/include/unicode/gregocal.h
./usr/local/include/unicode/unistr.h
./usr/local/include/unicode/currpinf.h
./usr/local/include/unicode/stsearch.h
./usr/local/include/unicode/measure.h
./usr/local/include/unicode/ureldatefmt.h
./usr/local/include/unicode/msgfmt.h
./usr/local/include/unicode/normlzr.h
./usr/local/include/unicode/ptypes.h
./usr/local/include/unicode/ustring.h
./usr/local/include/unicode/appendable.h
./usr/local/include/unicode/docmain.h
./usr/local/include/unicode/fieldpos.h
./usr/local/include/unicode/regex.h
./usr/local/include/unicode/platform.h
./usr/local/include/unicode/rbbi.h
./usr/local/include/unicode/tmunit.h
./usr/local/include/unicode/ugender.h
./usr/local/include/unicode/calendar.h
./usr/local/include/unicode/urep.h
./usr/local/include/unicode/smpdtfmt.h
./usr/local/include/unicode/numfmt.h
./usr/local/include/unicode/schriter.h
./usr/local/include/unicode/unifunct.h
./usr/local/include/unicode/uvernum.h
./usr/local/include/unicode/unirepl.h
./usr/local/include/unicode/rbtz.h
./usr/local/include/unicode/dtintrv.h
./usr/local/include/unicode/ubidi.h
./usr/local/include/unicode/fmtable.h
./usr/local/include/unicode/urename.h
./usr/local/include/unicode/ucol.h
./usr/local/include/unicode/timezone.h
./usr/local/include/unicode/tmutfmt.h
./usr/local/include/unicode/usetiter.h
./usr/local/include/unicode/tblcoll.h
./usr/local/include/unicode/selfmt.h
./usr/local/include/unicode/enumset.h
./usr/local/include/unicode/strenum.h
./usr/local/include/unicode/unifilt.h
./usr/local/include/unicode/ucat.h
./usr/local/include/unicode/parseerr.h
./usr/local/include/unicode/ucharstrie.h
./usr/local/include/unicode/tzrule.h
./usr/local/include/unicode/region.h
./usr/local/include/unicode/ucnv_cb.h
./usr/local/include/unicode/dtrule.h
./usr/local/include/unicode/ufieldpositer.h
./usr/local/include/unicode/utf.h
./usr/local/include/unicode/utypes.h
./usr/local/include/unicode/utrace.h
./usr/local/include/unicode/plurfmt.h
./usr/local/include/unicode/dtitvinf.h
./usr/local/include/unicode/utext.h
./usr/local/include/unicode/putil.h
./usr/local/include/unicode/tztrans.h
./usr/local/include/unicode/coll.h
./usr/local/include/unicode/icudataver.h
./usr/local/include/unicode/listformatter.h
./usr/local/include/unicode/uregex.h
./usr/local/include/unicode/udat.h
./usr/local/include/unicode/uset.h
./usr/local/include/unicode/localpointer.h
./usr/local/include/unicode/udata.h
./usr/local/include/unicode/plurrule.h
./usr/local/include/unicode/dtptngen.h
./usr/local/include/unicode/uregion.h
./usr/local/include/unicode/tznames.h
./usr/local/include/unicode/measfmt.h
./usr/local/include/unicode/umsg.h
./usr/local/include/unicode/unorm2.h
./usr/local/include/unicode/idna.h
./usr/local/include/unicode/filteredbrk.h
./usr/local/include/unicode/tzfmt.h
./usr/local/include/unicode/utf32.h
./usr/local/include/unicode/resbund.h
./usr/local/include/unicode/uchriter.h
./usr/local/include/unicode/parsepos.h
./usr/local/include/unicode/scientificnumberformatter.h
./usr/local/include/unicode/unum.h
./usr/local/include/unicode/unorm.h
./usr/local/include/unicode/tmutamt.h
./usr/local/include/unicode/ulistformatter.h
./usr/local/include/unicode/uclean.h
./usr/local/include/unicode/uiter.h
./usr/local/include/unicode/ucurr.h
./usr/local/include/unicode/measunit.h
./usr/local/include/unicode/ucharstriebuilder.h
./usr/local/include/unicode/uconfig.h
./usr/local/include/unicode/ubrk.h
./usr/local/include/unicode/gender.h
./usr/local/include/unicode/format.h
./usr/local/include/unicode/dtfmtsym.h
./usr/local/include/unicode/rep.h
./usr/local/include/unicode/stringpiece.h
./usr/local/include/unicode/locdspnm.h
./usr/local/include/unicode/sortkey.h
./usr/local/include/unicode/unumsys.h
./usr/local/include/unicode/ustream.h
./usr/local/include/unicode/ucnvsel.h
./usr/local/include/unicode/uchar.h
./usr/local/include/unicode/utf8.h
./usr/local/include/unicode/usearch.h
./usr/local/include/unicode/ucnv_err.h
./usr/local/include/unicode/stringtriebuilder.h
./usr/local/include/unicode/bytestrie.h
./usr/local/include/unicode/uldnames.h
./usr/local/include/unicode/ures.h
./usr/local/include/unicode/udisplaycontext.h
./usr/local/include/unicode/bytestream.h
./usr/local/include/unicode/errorcode.h
./usr/local/include/unicode/std_string.h
./usr/local/include/unicode/currunit.h
./usr/local/include/unicode/alphaindex.h
./usr/local/include/unicode/uformattable.h
./usr/local/include/unicode/choicfmt.h
./usr/local/include/unicode/basictz.h
./usr/local/include/unicode/symtable.h
./usr/local/include/unicode/uidna.h
./usr/local/include/unicode/utf16.h
./usr/local/include/unicode/ustringtrie.h
./usr/local/include/unicode/ushape.h
./usr/local/include/unicode/ustdio.h
./usr/local/include/unicode/uversion.h
./usr/local/include/unicode/datefmt.h
./usr/local/include/unicode/ucnv.h
./usr/local/include/unicode/compactdecimalformat.h
./usr/local/include/unicode/uobject.h
./usr/local/include/unicode/icuplug.h
./usr/local/include/unicode/utrans.h
./usr/local/include/unicode/dcfmtsym.h
./usr/local/include/unicode/rbnf.h
./usr/local/include/unicode/search.h
./usr/local/include/unicode/simpletz.h
./usr/local/include/unicode/usprep.h
./usr/local/include/unicode/dbbi.h
./usr/local/include/unicode/unimatch.h
./usr/local/include/unicode/umisc.h
./usr/local/include/unicode/uloc.h
./usr/local/include/unicode/simpleformatter.h
./usr/local/include/unicode/uspoof.h
./usr/local/include/unicode/upluralrules.h
./usr/local/include/unicode/ucasemap.h
./usr/local/include/unicode/uscript.h
./usr/local/include/unicode/curramt.h
./usr/local/include/unicode/ucsdet.h
./usr/local/include/unicode/chariter.h
./usr/local/include/unicode/translit.h
./usr/local/include/unicode/utf_old.h
./usr/local/include/unicode/udatpg.h
./usr/local/include/unicode/uniset.h
./usr/local/include/unicode/udateintervalformat.h
./usr/local/include/unicode/ucal.h
./usr/local/include/unicode/dtitvfmt.h
./usr/local/include/unicode/reldatefmt.h
./usr/local/include/unicode/vtzone.h
./usr/local/include/unicode/messagepattern.h
./usr/local/include/unicode/uenum.h
./usr/local/include/unicode/bytestriebuilder.h
./usr/local/include/unicode/locid.h
./usr/local/include/unicode/umachine.h
./usr/local/include/unicode/decimfmt.h
./usr/local/include/unicode/brkiter.h
./usr/local/include/unicode/normalizer2.h
./usr/local/include/unicode/utmscale.h
./usr/local/include/unicode/numsys.h
./usr/local/include/unicode/fpositer.h
./usr/local/bin/gencnval
./usr/local/bin/uconv
./usr/local/bin/icu-config
./usr/local/bin/genbrk
./usr/local/bin/gendict
./usr/local/bin/gencfu
./usr/local/bin/icuinfo
./usr/local/bin/genrb
./usr/local/bin/pkgdata
./usr/local/bin/makeconv
./usr/local/bin/derb
```

Does that help you at all @crummel?

**Comment by wfurt** [comment]
note that runtime dropped support for centos6 in master. Maybe we can also move to newer version. cc: @janvorli @tarekgh

**Comment by tarekgh** [comment]
@janvorli pointed before there is a copy https://sourceforge.net/projects/icu/files/ICU4C/57.1/icu4c-57_1-RHEL6-x64.tgz/download. I think we need to store this version somewhere if we need to continue using it. 

> Maybe we can also move to newer version

Looks ICU is not building for RHEL/Centos anymore. so, we'll have to build a version for that ourselves as we'll not find any available one to download.

**Comment by janvorli** [comment]
> note that runtime dropped support for centos6 in master. Maybe we can also move to newer version.

We still need to support CentOS 6 on .NET Core 3.1.

**Comment by wfurt** [comment]
> We still need to support CentOS 6 on .NET Core 3.1.

yes, I know but could we do it with existing containers? It seems like we may need to build ICU instead of using prebuilds. If we do, what version should we try to build?

**Comment by janvorli** [comment]
Ah, I am sorry for misunderstanding. If we build it ourselves, I would try to build the latest stable and if it doesn't work due to some Centos 6 issues, then find the newest one that can be built.

**Comment by wfurt** [comment]
That would still mean we stop building Cento6 images and support 3.1 with existing containers. 
I'm not sure if this _could_ work. That would defer work until we need to touch Centos6 again.

**Comment by janvorli** [comment]
No, I didn't mean that. I meant building ICU in the CentOS 6 container.

**Comment by tarekgh** [comment]
@janvorli why we need to try to do that for Centos 6 if we support it for servicing only? I mean why we can't just use https://sourceforge.net/projects/icu/files/ICU4C/57.1/icu4c-57_1-RHEL6-x64.tgz/download?

**Comment by janvorli** [comment]
We can use that. I was just responding to the question on building stuff.
But it seems we would need to expose that ICU for our users too. They need to download and install it too to be able to use globalization. We were pointing them to the icu site, but since that's not available anymore, we need to point them to some other source. I have no idea for how long that tarball is going to be available on the sourceforge, so it seems it would be safer to expose it on some server that we control.

**Comment by MichaelSimons** [comment]
What is the RHEL recommendation on where to get libicu?  What is the impact on our customers using RHEL/centos 6?  We document the use of http://download.icu-project.org/files/icu4c/57.1/icu4c-57_1-RHEL6-x64.tgz in the [instructions here](https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md#icu).

**Comment by janvorli** [comment]
> We document the use of http://download.icu-project.org/files/icu4c/57.1/icu4c-57_1-RHEL6-x64.tgz in the [instructions here](https://github.com/dotnet/core/blob/master/Documentation/build-and-install-rhel6-prerequisites.md#icu).

This file is no longer available at that URL, so that's a problem both for us rebuilding the docker images and our customers using .NET Core on RHEL/CentOS 6

**Comment by dleeapho** [comment]
@omajid is there Red Hat guidance on installing ICU for RHEL/CentOS 6? This affects our .NET Core customers running on those distro versions but it surely has wider implications.

**Comment by janvorli** [comment]
Please note there is an official package of ICU for RHEL/CentOS 6, but it is too ancient (I think it is version 4.91). We cannot work with anything below version 50 (ICU versioning schema has changed, so the 50 comes after 4.x).

**Comment by tarekgh** [comment]
I am talking offline with @jefgen trying to figure out if we can restore the link file http://download.icu-project.org/files/icu4c/57.1/icu4c-57_1-RHEL6-x64.tgz to the ICU download server. we'll ask for that but not sure what we'll get. meanwhile, we can ask customers to use  https://sourceforge.net/projects/icu/files/ICU4C/57.1/icu4c-57_1-RHEL6-x64.tgz/download for now.

**Comment by omajid** [comment]
@dleeapho AFAIK, RHEL 6 includes icu 4.2.1, and that's the only one supported by Red Hat on RHEL 6 :(

**Comment by jefgen** [comment]
> if we can restore the link file http://download.icu-project.org/files/

Unfortunately, the server that used to host the various downloads for ICU at that location now longer exists anymore.

The downloads for ICU are hosted on GitHub now, though I don't think older versions of pre-built binaries were mirrored/copied over to GitHub as they were/are available on Source Forge.

You should be able to use the pre-built binaries from there for now, though I can ask the ICU-TC if maybe they can also be uploaded to the older GitHub releases as well to provide two download locations.

**Comment by Bob-Davis** [comment]
Is there some specific feature in 50 that is required, or is it a patch that's needed?

**Comment by janvorli** [comment]
The version 50 was a large change compared to the previous versions. The doc says: _ICU 50 is a major release of ICU, with new features, new APIs and many bug fixes in data and code._ 
I the past, I have thought that the difference in the API were so large that there was no way to make our stuff reasonably work on the pre-50 APIs, but now I don't remember how I got this information and how correct it was. @tarekgh may know more details here.

**Comment by tarekgh** [comment]
I believe there is some functionality which we use and is introduced in at least v49 e.g. `unorm2_getNFCInstance`. Actually we should prefer v53 to avoid using some deprecated APIs like `ucol_setVariableTop`. fortunately, we handle this case in the code to not strictly require 53.

**Comment by Bob-Davis** [comment]
ahh - ok, that makes sense. Thanks.

**Comment by jefgen** [comment]
> I can ask the ICU-TC if maybe they can also be uploaded to the older GitHub releases as well to provide two download locations.

I have a bit of good news -- I was able to upload the binaries for older versions to the GitHub releases. So the ICU [download page](http://site.icu-project.org/download/) links should now work for versions going back to ICU 56.

The last release of public ICU which provided pre-built binaries for RHEL6 looks to be ICU 57.

You can download it from the release here:
 https://github.com/unicode-org/icu/releases/tag/release-57-1

Or directly from:
https://github.com/unicode-org/icu/releases/download/release-57-1/icu4c-57_1-RHEL6-i386.tgz
https://github.com/unicode-org/icu/releases/download/release-57-1/icu4c-57_1-RHEL6-x64.tgz

**Comment by tarekgh** [comment]
Thanks a lot, @jefgen. This should unblock us.
