### ISSUE TITLE
Add Server Core pre-req image to enable testing with Server Core

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-buildtools-prereqs-docker#316]
We have a Nano Server image. We should have a Server Core variant to enable the same testing patterns/coverage with Server Core.

https://github.com/dotnet/dotnet-buildtools-prereqs-docker/tree/master/src/nanoserver/1809/helix/amd64

**Comment by MichaelSimons** [comment]
Matt, can you help create this image so that we can get the product teams testing on Server Core images?

**Comment by MattGal** [comment]
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/317/

**Comment by mthalman** [comment]
Images are published.  See https://github.com/dotnet/versions/commit/d71ea62b5b6d3aa55eba0886b13ee06287bdadd9 and https://github.com/dotnet/versions/commit/81fd3c98e22bc1460930f2a448586f24fb67de56 for tags.
