### ISSUE TITLE
Prepare crossrootfs for ppc64le

### ISSUE THREAD

**Issue by krishvoor** [dotnet/dotnet-buildtools-prereqs-docker#346]
The intent of this issue is to create equivalent crossrootfs for ppc64le via
 updating the required Dockerfile(s) and script(s) - preliminary findings indicate Ubuntu sources that needs to be edited.
 
1) https://github.com/dotnet/dotnet-buildtools-prereqs-docker/tree/master/src/ubuntu 
2) https://github.com/dotnet/dotnet-buildtools-prereqs-docker/tree/master/src/ubuntu/build-scripts

**Comment by krishvoor** [comment]
I would like to work on this Issue - please help assign.

**Comment by mthalman** [comment]
Can you describe or link to the broader set of work this is related to?

**Comment by krishvoor** [comment]
We ( IBM ) would like to contribute and enable dotnet/runtime on IBM Power Systems ( ppc64le arch ).

After understanding the dotnet/runtime build process  - cross-compiling dotnet/runtime via x86_64 ( Intel ) Systems - seems 
to be the best fit - as the native compilation of dotnet/runtime needs SDK Binaries/Libraries - and there is a circular dependency to build them.

Hence after careful evaluation, I believe having a debootstrapp'd ubuntu-ppc64el rootfs image inside x86_64 would help us to get kick-started with cross-compilation effort and equivalent PR(s)

Can you kindly guide where I can request new architecture (ppc64el) support for dotnet/runtime repo to be added?

**Comment by mthalman** [comment]
This particular issue to provide a Docker image for runtime developers seems a bit premature at this point.  I see two existing issues proposing support for PowerPC (https://github.com/dotnet/runtime/issues/10055, https://github.com/dotnet/runtime/issues/13277).  Not sure which of them would take priority.

cc @richlander

**Comment by krishvoor** [comment]
Looking at Issues [#13277](dotnet/runtime#13277) & [#10055](dotnet/runtime#10055)  - I believe [#13277](dotnet/runtime#13277) should take prefrence .. 

However - dotnet/runtime has now evolved (i.e. consolidated-repo(s) ) since last year - per my findings cross-compiling with **dotnet-buildtools-prereqs-docker** seems to be a better approach - as native compilation has its limitations.

**Comment by jkotas** [comment]
The docker images from this repo are for our CI systems. Having a discussion about adding one for PowerPC cross compilation makes sense only once the port is working to some degree and we agree that it is worth protecting it via CI validation.

**Comment by MichaelSimons** [comment]
Until ppc64le is supported by the framework and there is a need for a dotnet-buildtools-prereqs image, there is no value in keeping this issue open.
