### ISSUE TITLE
CentOS 6 build failing - unable to retrieve repo metadata for base

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#384]
Attempting to build the Dockerfile for CentOS 6 at https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/master/src/centos/6/Dockerfile yields the following error:

```
Sending build context to Docker daemon  7.168kB

Step 1/9 : FROM centos:6
 ---> d0957ffdf8a2
Step 2/9 : RUN yum install -y         centos-release-SCL         epel-release         scl-utils-build         wget     &&     rpm --import http://linuxsoft.cern.ch/cern/slc6X/x86_64/RPM-GPG-KEY-cern &&     wget -O /etc/yum.repos.d/slc6-devtoolset.repo http://linuxsoft.cern.ch/cern/devtoolset/slc6-devtoolset.repo &&     yum install -y         "perl(Time::HiRes)"         autoconf         automake         byacc         devtoolset-7-gcc*         doxygen         expat-devel         gdb         gettext-devel         git         krb5-devel         libedit-devel         libidn-devel         libmetalink-devel         libnghttp2-devel         libssh2-devel         libtool         libunwind-devel         libuuid-devel         lttng-ust-devel         lzma         ncurses-devel         numactl-devel         openssl-devel         pcre-devel         perl-devel         python-argparse         python27         readline-devel         python34         sudo         xz         zlib-devel     &&     yum clean all
 ---> Running in dc90237fbc9d
Loaded plugins: fastestmirror, ovl
Setting up Install Process
Error: Cannot retrieve repository metadata (repomd.xml) for repository: base. Please verify its path and try again
YumRepo Error: All mirror URLs are not using ftp, http[s] or file.
 Eg. Invalid release/repo/arch combination/
removing mirrorlist with no valid mirrors: /var/cache/yum/x86_64/6/base/mirrorlist.txt
```

**Comment by mthalman** [comment]
@omajid - Any ideas on this?

**Comment by mthalman** [comment]
Oh, I see that CentOS 6 is EOL as of Nov 30.

@MattGal - Are there any builds still configured to use this?

**Comment by omajid** [comment]
I think our (older) servicing releases still use these? I seem to recall reading that .NET 5 doesn't support CentOS 6.

**Comment by MattGal** [comment]
> Oh, I see that CentOS 6 is EOL as of Nov 30.
> 
> @MattGal - Are there any builds still configured to use this?

At least for teams like the .NET Core runtime, I don't think so; oldest currently supported version is 2.1 which shows Centos 7 not 6 support:

https://github.com/dotnet/corefx/tree/release/2.1

That said I'd assume the images already pushed to mcr / dockerhub would keep working unless someone tries to do packaging actions inside them no?  That's all the builds would use.

**Comment by mthalman** [comment]
Yes, the Docker images that have already been published aren't going anywhere.  The question is whether this Dockerfile needs to be maintained at all to produce new images in the future or if it can just be deleted.

**Comment by MattGal** [comment]
> Yes, the Docker images that have already been published aren't going anywhere. The question is whether this Dockerfile needs to be maintained at all to produce new images in the future or if it can just be deleted.

Pretty sure it's the "can just be deleted" option since 2.1 and higher don't build there; tagging @leecow and @marcpopMSFT for visibility.

Looking at the corefx builds for 2.1, I only see these tags getting used in build:
```
microsoft/dotnet-buildtools-prereqs:alpine-3.6-3148f11-20171119021156
microsoft/dotnet-buildtools-prereqs:ubuntu-16.04-cross-arm64-a3ae44b-20180315221921
```
... though I think there is an AMD64 Ubuntu in there somewhere.

**Comment by leecow** [comment]
We've never 'officially' supported CentOS 6.
