### ISSUE TITLE
ubuntu_14 blocked: failure during npm package install "Error: CERT_UNTRUSTED"

### ISSUE THREAD

**Issue by dagood** [dotnet/dotnet-buildtools-prereqs-docker#43]
This fails CI and the official image builds:

```
00:05:51.974 npm http GET https://registry.npmjs.org/azure-cli/0.9.15
00:06:52.015 npm ERR! Error: CERT_UNTRUSTED
...
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "-g" "azure-cli@0.9.15"
```

Answers to https://stackoverflow.com/q/21855035 suggest updating `npm` or forcing the connection to be allowed.

**Comment by RussKeldorph** [comment]
@dotnet/dncenghot @dleeapho @richlander per @MichaelSimons OOF

Can we get somebody looking at this?  It's urgent for .NET Core 2.1 since this is blocking a critical fix for ARM.

/cc @Petermarcu @ianhays

**Comment by dleeapho** [comment]
@dagood PTAL

**Comment by dagood** [comment]
On it.

**Comment by dagood** [comment]
The root problem is that the old `npm`'s cert has expired. (https://stackoverflow.com/q/21855035.) https://stackoverflow.com/a/39113115 explains how the certs are embedded in this old version. Disabling the cert check seems like the wrong solution to me, since that *might* open us up to MITM.

Updating `npm` (which requires an upgrade to `node` to match) seems like the way to go. There are some build issues that happen with the upgrade that I tried to fix, see the PR: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/46.

**Comment by dagood** [comment]
This CI block was fixed, but the official build still failed: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/47. Retrying to see if it's just flaky, but there might be more work there.
