### ISSUE TITLE
Remove Ubuntu 16.04 (Xenial) Dockerfiles due to EOL

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#443]
It reached EOL in April 2021.

**Comment by mthalman** [comment]
Current references to these tags: https://grep.app/search?q=dotnet-buildtools/prereqs%3Aubuntu-16.04

**Comment by MichaelSimons** [comment]
[Triage] Ubuntu 16.04 is still in extended support (ESM) until the first part of 2024.  Given we are continuing to run 16.04 build/test legs, we should continue to produce this image as long as the base images are being serviced.

Keeping this open to ensure the base image is getting service updates.

**Comment by mthalman** [comment]
Confirmed that Ubuntu 16.04 Docker image is still being serviced.  It was just updated today.  Closing this.
