### ISSUE TITLE
Ubuntu 14.04 official build flaky: apt-get "Failed to fetch" "Hash Sum mismatch"

### ISSUE THREAD

**Issue by dagood** [dotnet/dotnet-buildtools-prereqs-docker#47]
https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1560649

```
W: Size of file /var/lib/apt/lists/archive.ubuntu.com_ubuntu_dists_trusty-updates_main_binary-amd64_Packages.gz is not what the server reported 1328333 1328339
W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/main/binary-amd64/Packages  Hash Sum mismatch

W: Failed to fetch http://archive.ubuntu.com/ubuntu/dists/trusty-updates/universe/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
Error executing command, exiting
The command '/bin/sh -c apt-get update     && apt-get install -y wget     && wget -O - https://deb.nodesource.com/setup_8.x | bash     && apt-get install -y         git         zip         tar         nodejs     && rm -rf /var/lib/apt/lists/*     && npm install -g azure-cli@0.9.15 --unsafe-perm=true     && npm cache clean -f' returned a non-zero code: 1
```

I'm rerunning in case this is just flakiness (it didn't happen in CI). https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1560916

This solution sounds like what we need, and we already do the `rm -rf /var/lib/apt/lists/*` in some Dockerfiles: https://unix.stackexchange.com/a/273441

> You can delete the cached metadata on your system and try again. To do this, first run `apt-get clean` followed by `rm -rf /var/lib/apt/lists/*`. Next, run `apt-get update`. This will re-download all the metadata. If the repository you are trying to connect to doesn't update itself while you are running `apt-get update`, you will be fine. Otherwise, you'll have to do this again.

**Comment by dagood** [comment]
The retry succeeded. (Took 2 hours, for the record. The first attempt failed after ~30 minutes.) This is just a potential build flakiness issue now.

**Comment by MichaelSimons** [comment]
Docker doesn't support native constructs for retrying.  Writing retry logic is possible but ugly and not standard Dockerfile logic.  Closing as this is not a priority at the moment.  If this happens more often, then we can reconsider.

**Comment by dagood** [comment]
Retry isn't the proposed solution: the SO answer suggests that `apt-get clean` followed by `rm -rf /var/lib/apt/lists/*` fixes this, and that's already in some of our Dockerfiles.

Agreed on priority though.
