### ISSUE TITLE
add  gss-ntlmssp to dotnet docker images

### ISSUE THREAD

**Issue by wfurt** [dotnet/dotnet-buildtools-prereqs-docker#49]
This is related to https://github.com/dotnet/corefx/issues/28961 and https://github.com/dotnet/wcf/issues/943

Without this NTLM authentication will not work. In the past that would impact only NegotiateStream but in 2.1 this also impacts HTTPClient so the exposure is bigger.

**Comment by MichaelSimons** [comment]
@wfurt - Can you clarify which specific images you want `gss-ntlmssp` added to?

**Comment by wfurt** [comment]
I look and I was not sure @MichaelSimons. If I know, I would probably craft PR. 

I would like to see it in all .NET Core 2.1*  Linux docker images. 
https://hub.docker.com/r/microsoft/dotnet/

It seems like we publish *stretch* and *bionic* e.g. Debian and Ubuntu. 
Proper place would be somewhere in "runtime-deps".
It seems like arm32 and arm64 exist as well - but I did not test the actual functionality. 

Is that sufficient information?

**Comment by MichaelSimons** [comment]
@wfurt - thanks for the clarification.  I was suspecting you meant the microsoft/dotnet images but wasn't certain.

**Comment by MichaelSimons** [comment]
Issue moved to [dotnet/dotnet-docker #478](https://github.com/dotnet/dotnet-docker/issues/478) via [**ZenHub**](https://www.zenhub.com/)
