### ISSUE TITLE
New container request

### ISSUE THREAD

**Issue by aik-jahoda** [dotnet/dotnet-buildtools-prereqs-docker#502]
As part of an update of the build matrix (dotnet/runtime#57947) we need to target a new OS. The specific containers doesn't exist or I wasn't able to identify the correct one.

All containers are for helix queues:

- [x] ~~RHEL 8~~ we will use Centos8
- [ ] Fedora 35 #509
- [x] Windows Server Core 20H2 #513
- [x] Ubuntu 21.04 #510
- [x] openSUSE 15 #512

/cc @ViktorHofer

**Comment by mthalman** [comment]
Note that Windows doesn't provide container images for WS 2012.  The earliest version for which they do have images is 2016.

**Comment by ViktorHofer** [comment]
2012 is not the year but the version number in this case, also called 20H2.

**Comment by mthalman** [comment]
> 2012 is not the year but the version number in this case, also called 20H2.

The official name for the release is 20H2 so please use that instead.

**Comment by wfurt** [comment]
I can do the 'Fedora 35` I want to update MsQuic for runtime/main and this would be good fit. I assume Centos8 would be sufficient for the RHEL8 right? I can probably look at it as well.

**Comment by aik-jahoda** [comment]
Closing uncompleted as Fedora 35 has an issue:  #509
