### ISSUE TITLE
Debian docker image for dotnet/runtime tests is missing `ps`

### ISSUE THREAD

**Issue by ManickaP** [dotnet/dotnet-buildtools-prereqs-docker#565]
Discovered in https://github.com/dotnet/runtime/pull/63963, build https://dev.azure.com/dnceng/public/_build/results?buildId=1567505&view=results.

A test is being added which calls `ps` from command line. It works on most of the Linuxes we run the tests on a PR, but it seems to fail on `mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-20210304164434-56c6673` with:
```
System.ComponentModel.Win32Exception : An error occurred trying to start process 'ps' with working directory '/root/helix/work/workitem/e'. No such file or directory
```
As part of the PR, a check if `ps` is supported will be added, but @safern recommended to also add the command into our images.

Note that the command might be missing from more images depending on where we do and don't run tests during PRs.

I'm willing to put up a PR to add `procps`, I'd just need a bit help locating the right Dockerfiles. I'm also not sure if the change needs to be followed by a change in runtime repo.

**Comment by mthalman** [comment]
The Dockerfile that maps to `mcr.microsoft.com/dotnet-buildtools/prereqs:debian-10-helix-amd64-20210304164434-56c6673` is https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/debian/10/helix/amd64/Dockerfile. I would recommend making the same change to the Dockerfiles for the other architectures as well: [arm32](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/debian/10/helix/arm32v7/Dockerfile), [arm64](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/debian/10/helix/arm64v8/Dockerfile).

This would require an update to the runtime repo to target the newly created Docker tag produced by the change:
- https://github.com/dotnet/runtime/blob/main/eng/pipelines/libraries/helix-queues-setup.yml
- https://github.com/dotnet/runtime/blob/main/eng/pipelines/coreclr/templates/helix-queues-setup.yml

**Comment by wfurt** [comment]
While I'm not opposing the change, should `SupportsGettingThreadsWithPsCommandOnLinux` in the test be sufficient? It feels like something is not right about the platform detection.

**Comment by ManickaP** [comment]
@wfurt the detection is new, added in that PR. The goal is to do both, detection and adding support, this issue is about the latter.

> As part of the PR, a check if ps is supported will be added, but @safern Santiago Fernandez Madero FTE recommended to also add the command into our images.
