### ISSUE TITLE
Force rebuild of an image

### ISSUE THREAD

**Issue by ManickaP** [dotnet/dotnet-buildtools-prereqs-docker#593]
Can we trigger rebuild of fedora-34-helix image?
The dockerfile contains [instructions to pull and build](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/dcc36f08baa367d98f9c6cfcdde28fc0d5f6c6d9/src/fedora/34/helix/amd64/Dockerfile#L25-L34) newest msquic and we'd like to consume the newer version in dotnet/runtime.

Related change in runtime: https://github.com/dotnet/runtime/pull/67383

cc: @wfurt

**Comment by mthalman** [comment]
Started a build: https://dev.azure.com/dnceng/internal/_build/results?buildId=1692729&view=results

**Comment by wfurt** [comment]
BTW another option is to create new image - leave the fedora-34-helix for servicing 6.0 (with 1.9.x) and create 35 or 36 to track mainline with 2.x. 
Currently we don't have good structure in place to track multiple msquic versions.

**Comment by mthalman** [comment]
Build is complete. Closing
