### ISSUE TITLE
Update RHEL7 and CentOS7 images

### ISSUE THREAD

**Issue by rzikm** [dotnet/dotnet-buildtools-prereqs-docker#620]
Recently one of the external test servers we use for .NET networking functional tests changed certificates, and some of our tests started to fail: https://github.com/dotnet/runtime/issues/69664, I tried to create a VM with the same RHEL version which we run CI tests on and it turns out that some of the installed CA certs were long expired, updating the system (by `yum update`) resolved the issue. I assume the same is needed for the CentOS7 image.

I am not sure where are the Dockerfiles located, but the yml file for the related AzDO pipelines definition contains these:

```yml
          - ${{ if or(ne(parameters.jobParameters.isExtraPlatforms, true), eq(parameters.jobParameters.includeAllPlatforms, true)) }}:
            - (Centos.7.Amd64.Open)Ubuntu.1604.Amd64.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-mlnet-helix-20210714125435-dde38af
            - RedHat.7.Amd64.Open
```

Can you please rebuild them/update them?

**Comment by wfurt** [comment]
We can update Centos.7 but I don't think the `RedHat.7` comes from here. 
We will probably needs Arcade issue if we want to update Helix queue. 
cc: @MattGal 

note that `centos-7-mlnet-helix-20220505130359-dde38af` already exist. If that is sufficient we can simply update runtime config @rzikm (not sure why we need mlnet but it probably does not hurt)

**Comment by MattGal** [comment]
For the Centos case, self-service update of the docker image is the way to go; you might not need the ML.NET version of the image though?  

For RHEL, I created https://github.com/dotnet/arcade/issues/9462 to track us doing this; we have support for it but it was turned off, this may turn out to be for a reason (but we'll find out).  Due to the challenges of datacenter migration it may be a bit before this rolls out, I fear; feel free to use precommands to call yum update in the meantime if it's important.

**Comment by mthalman** [comment]
CentOS 7 image is rebuilt: `mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-mlnet-20220526152527-dde38af`

**Comment by mthalman** [comment]
Correction: this is the new image: `mcr.microsoft.com/dotnet-buildtools/prereqs:centos-7-mlnet-helix-20220526185130-dde38af`

**Comment by rzikm** [comment]
I assume I should put it in one of the parent Dockerfiles, and not the most specific one inside the mlnet/helix folder?

**Comment by wfurt** [comment]
should we run update on all packages to stay current e.g. simulate what customers _should_ be running? 
The `ca-certificates` has no real dependencies so it is OK if it is out of sync with the rest but if we are running old packages we may miss some other changes.
