### ISSUE TITLE
[Linux Arm64] Infrastructure does not support building linux arm64v8 images

### ISSUE THREAD

**Issue by jashook** [dotnet/dotnet-buildtools-prereqs-docker#71]
In order to build the following images we need the ability to run build cross architecture docker builds.

| base image | arch | requires arm64 emulation or hardware | Example dockerfile |
|-------------|-----|------------------------------------|----------
| arm64v8/ubuntu:16.04 | arm64 | yes | https://gist.github.com/jashook/9eb11fa6228901234baecee195f8b19e |
| arm64v8/ubuntu:16.04 or ubuntu:16.04 | armhf | maybe |https://gist.github.com/jashook/5b0daff1f00e8bf92e41909e033081ea|
| arm64v8/alpine:3.6 | arm64 | yes |https://gist.github.com/jashook/2515f81048ada333f664337754af4702|
| arm64v8/debian:9 | arm64 | yes | https://gist.github.com/jashook/08a3c23e8f71d39e115b9f14694ca67d|

We should these docker images on arm64 hardware

**Comment by RussKeldorph** [comment]
@wfurt FYI

**Comment by wfurt** [comment]
note that Alpine 3.9 is out. It may be mainstream before we ship.

**Comment by MichaelSimons** [comment]
#72 will add the necessary support for ARM images.  When adding arm images to the manifest, you will need to specify two additional properties - `architecture` & `variant`.  The following manifest snippet illustrates their usage.

```
        {
          "platforms": [
            {
              "architecture": "arm64",
              "dockerfile": "src/ubuntu/16.04/arm64v8",
              "os": "linux",
              "tags": {
                "ubuntu-16.04-arm64v8-$(System:DockerfileGitCommitSha)-$(System:TimeStamp)": {}
              },
              "variant": "v8"
            }
          ]
        },
        {
          "platforms": [
            {
              "architecture": "arm",
              "dockerfile": "src/ubuntu/16.04/arm32v7",
              "os": "linux",
              "tags": {
                "ubuntu-16.04-arm32v7-$(System:DockerfileGitCommitSha)-$(System:TimeStamp)": {}
              },
              "variant": "v7"
            }
          ]
        },
```
