### ISSUE TITLE
Link in "About" section of GitHub is dead

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-buildtools-prereqs-docker#724]
This one (mcr.microsoft.com/dotnet-buildtools/prereqs): 
<img width="527" alt="image" src="https://user-images.githubusercontent.com/36081148/195645291-52251e37-3651-4bb7-90ef-72b797c7241a.png">

**Comment by mthalman** [comment]
This is by design. The images in that repo are not publicly supported but just tools for the .NET build system and .NET source developer community. That's why there's no official documentation page for it on the MAR portal.

**Comment by lbussell** [comment]
I see, thanks, you're not supposed to actually visit that link.
