### ISSUE TITLE
Need a way to distinguish staging images from production images for timestamp-based tags

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#761]
The tagging pattern used for the images in this repo is the following:

https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/b85260ccbde5606a8fa8122cd989038130c3ac76/src/ubuntu/manifest.json#L13-L14

The `FloatingTagSuffix` variable is only applied to the floating tag. The `FloatingTagSuffix` variable is what indicates whether the tag is staging or production (it's set to `staging` if a staging image or (blank) if production). But for the timestamp-based tags, there's no such distinction. So when people do want to use a timestamp based tag, they'll look them up in https://mcr.microsoft.com/v2/dotnet-buildtools/prereqs/tags/list and see a bunch of them listed but there's no way to tell if it's from staging or production.

I think the appropriate thing to do is rename `FloatingTagSuffix` to something like `QualityTagSuffix` and apply it to both tag types.

**Comment by mthalman** [comment]
[Triage]
It would be best if the variable wasn't actually a suffix but rather inserted in the tag value to help better organize the list of tags.

e.g. 
`"ubuntu-18.04$(Quality)-$(System:TimeStamp)-$(System:DockerfileGitCommitSha)": {},`

Defining it this way would group all the "staging" tags together for a given image type, for example, when listed alphabetically.

**Comment by lbussell** [comment]
[Triage] This is no longer an issue since we are not shipping out of a staging branch today.
