### ISSUE TITLE
Remove use of local tags

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#765]
Prior to the implementation of [floating tags](https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/667) in this repo, we relied on "local" tags to use as the referenced tags in the `FROM` instruction for dependent Dockerfiles.

For example, the WASM Dockerfile at https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/441a2e565074a9d4e58411dbbd9772e8096c20d9/src/ubuntu/20.04/helix/wasm/amd64/Dockerfile depends on the image produced by the Helix Dockerfile at https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/441a2e565074a9d4e58411dbbd9772e8096c20d9/src/ubuntu/20.04/helix/amd64/Dockerfile. Its `FROM` instruction references `mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-20.04-helix-amd64-local`. Since we use dynamically generated tags for all the images in the repo, it's not possible to use those tags, so a "local" tag is used instead. This local tag is defined in the manifest as:

https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/441a2e565074a9d4e58411dbbd9772e8096c20d9/src/ubuntu/manifest.json#L519-L524

Again, this was all implemented prior to the existence of the published floating tags. Now that we have these floating tags, we can use them instead, since they provide a well-known stable name that can be referenced.

So we should remove all the local tags and update the Dockerfiles to use the floating tags instead.

But doing that exposes us to a potential issue where a floating tag is referenced but no longer produced by the build. Using the previous example of WASM and Helix, let's say that the Helix Dockerfile and manifest entries get deleted but the WASM stuff is mistakenly left in and not updated. It will continue to reference the floating tag which will exist and allow the build to complete. But this is not what we'd want. The intention is that the WASM Dockerfile is based on the Helix Dockerfile so if the Helix Dockerfile is deleted, the build should fail for WASM.

This can be accomplished through the use of a staging repo prefix. This pattern is used in the https://github.com/dotnet/dotnet-docker repo. The images in this repo are already pushed to a staging location, it's just the Dockerfiles and manifest entries that need to be updated to reference it. This will avoid accidentally pulling an image from a public registry when the intention was to use the locally built image instead.

For example, the WASM Dockerfile would be changed to the following:

```Dockerfile
ARG REPO=mcr.microsoft.com/dotnet-buildtools/prereqs
ARG FLOATING_TAG_SUFFIX
FROM $REPO:ubuntu-20.04-helix-amd64${FLOATING_TAG_SUFFIX}
```

And the manifest entry to include the following field:

```json
"buildArgs": {
  "REPO": "$(Repo:prereqs)"
  "FLOATING_TAG_SUFFIX": "$(FloatingTagSuffix)"
}
```

This will dynamically set the `REPO` arg to the staging location of the repo (e.g. `dotnetdocker.azurecr.io/build-staging/<build-id>/dotnet-buildtools/prereqs`). In the case I warned about above, if the Helix Dockerfile were to be deleted, the build would fail because that tag wouldn't have been built and wouldn't exist at the staging location. This is the behavior we want.

**Comment by mthalman** [comment]
Technically the use of the `REPO` arg doesn't need to be done to avoid pulling from a public MCR image because Image Builder will [detect the referencing of a public MCR tag](https://github.com/dotnet/docker-tools/blob/1b7ae1f001019babc13388da6f068abcf919aecb/src/Microsoft.DotNet.ImageBuilder/src/Commands/BuildCommand.cs#L821-L853) and rewrite it to reference the locally built tag instead. But, it would be nice to use the `REPO` arg pattern anyway, because then we could just get rid of that logic in Image Builder.

**Comment by mthalman** [comment]
[Triage]
These changes may become obsolete depending on the work done by the Eng. Services team to dynamically generate Dockerfiles to have better maintenance.

@michellemcdaniel - What are your thoughts on any broad changes like this? How relevant would this pattern be in the system that Eng. Services is planning?

**Comment by michellemcdaniel** [comment]
This is something that we're basically planning on doing in the new thing. I don't see an issue with changing it here for now.

**Comment by MichaelSimons** [comment]
> This is something that we're basically planning on doing in the new thing. I don't see an issue with changing it here for now.

The concern I had is that the new thing we replace this.  Doing this now would have limited ROI.  @michellemcdaniel, is there a rough timeframe on the new thing?

**Comment by michellemcdaniel** [comment]
We're working on the conversion now, but it's taking us quite a bit longer than we expected to. I think for the full infrastructure to be finished and actually building and publishing all of the dockerfiles currently maintained in this repo, we are looking at some time in March. @ChadNedzlek does that sound right to you?

**Comment by ChadNedzlek** [comment]
Yup, that feels reasonable.  There are a lot of finicky differences between all the dockerfiles that are rarely explained, so we've got a lot of stuff to plow through.

**Comment by mthalman** [comment]
[Triage]
Putting this on the backlog for future work. But there are no immediate plans to implement this until Eng. Services has implemented the migration of these Dockerfiles to the new internal system. Since the raw Dockerfiles won't exist as they do today, things will likely be different. So no sense in spending time implementing these changes now when it may need to change again.

**Comment by mthalman** [comment]
There still may be a need to keep these local tags due to https://github.com/dotnet/docker-tools/issues/1130. If that issue were to be resolved, they can be used as a means of defining images which are not meant to be published.

**Comment by mthalman** [comment]
This is required in order to implement the solution for https://github.com/dotnet/docker-tools/issues/1417. In order to do the matrix trimming, we need to know what the current digest of a Dockerfile's base image. This doesn't work when the base image is a local tag reference: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/9624a696292675cd75ddf4d049118bf56fc7b1f7/src/alpine/3.18/WithNode/amd64/Dockerfile#L1C50-L1C67. It can't query for the digest because that tag doesn't exist in the registry.
