### ISSUE TITLE
Incorrect `sharedTags` use?

### ISSUE THREAD

**Issue by richlander** [dotnet/dotnet-buildtools-prereqs-docker#776]
What does this `sharedTags` property do? It doesn't seem like it is correct given the content of the rest of the file. I didn't see anything similar in the Alpine or CentOS variants of the same file.

https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/8012868764e5175e5c3d57d1307a17b36916898f/src/debian/manifest.json#L7-L9

**Comment by mthalman** [comment]
See this comment: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/752#issuecomment-1370144167. We use shared tags specifically for testrunner because it's convenient to have a multi-arch tag. But since a shared tag is not associated with a distinct git commit, we need a different tagging pattern from the other usages.

**Comment by MichaelSimons** [comment]
> What does this sharedTags property do?

The SharedTags property is how a manifest/multi-arch tag is defined with this infra.

**Comment by richlander** [comment]
I see. Is it saying "make a manifest tag for all the images that match `debian-buster-slim-docker-testrunner`"?

If so, why was it done for just buster and not any later versions and also not for other distros (like Alpine)?

**Comment by mthalman** [comment]
> I see. Is it saying "make a manifest tag for all the images that match `debian-buster-slim-docker-testrunner`"?

It's saying that the images built by the Dockerfiles defined within the scope of the JSON object defining these shared tags are to be grouped as a manifest list.

> If so, why was it done for just buster and not any later versions and also not for other distros (like Alpine)?

It's nothing to do with other distros. It's about the purpose of the Dockerfiles. These Dockerfiles are for the testrunner which is only used by the Docker infrastructure. No other teams have a need for multi-arch tags but it's convenient for our Docker infra's use of testrunner to have it.

**Comment by richlander** [comment]
If that's the case, why are we still using buster?

**Comment by mthalman** [comment]
> If that's the case, why are we still using buster?

We're not as of yesterday: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/752. 😉

**Comment by mthalman** [comment]
[Triage]
The purpose of these shared tags is scoped to just the test-runner images. No issue here.
