### ISSUE TITLE
Alpine install for pip is failing for Helix Dockerfile

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#796]
This seems limited to Alpine 3.13/3.14 for arm32. Failing build: https://dev.azure.com/dnceng/internal/_build/results?buildId=2108949&view=results (internal Microsoft link).

Error message:

```
  error: failed to get `pyo3` as a dependency of package `cryptography-rust v0.1.0 (/tmp/pip-install-m4ha1wge/cryptography_f2bd3052840644a780dff887d34f7c93/src/rust)`
```

I've tried updating the Dockerfile to latest versions of pip stuff and it didn't help:

```
python -m pip install --upgrade pip==23.0 && \
python -m pip install virtualenv==20.19.0 && \
```

**Comment by riarenas** [comment]
@MattGal any insights? I know you've been dealing with pip shenanigans in helix lately.

**Comment by riarenas** [comment]
@MattGal yeah. That build is now blocked forever due to the clone depth problems. You're saying there's a chance this is transient? we could try a new build.

**Comment by MattGal** [comment]
> @MattGal yeah. That build is now blocked forever due to the clone depth problems. You're saying there's a chance this is transient? we could try a new build.

Fairly certain based off the logs yeah.  Can we just make the automation clone at a depth of 10 vs 1 or something?  Seems like that would still work exactly as desired for the next 9 commits instead of insta-breaking.

**Comment by riarenas** [comment]
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/791 tracks the dotnet/versions cloning issue.

**Comment by mthalman** [comment]
@MattGal - I don't think this is a transient issue. I was able to repeatedly repro it by locally building https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/alpine/3.14/helix/arm32v7/Dockerfile.

**Comment by MattGal** [comment]
> @MattGal - I don't think this is a transient issue. I was able to repeatedly repro it by locally building https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/alpine/3.14/helix/arm32v7/Dockerfile.

Right on, I'll spend a few minutes wrestling with it when I finish my inbox and let you know if I find a viable workaround.

**Comment by ChadNedzlek** [comment]
https://github.com/pyca/cryptography/issues/5771

**Comment by ChadNedzlek** [comment]
Apparently the cryptography package just decided to give up support for a huge number of platforms. We need to pin the package back to a previous version and... never update it again? That sounds fun.

**Comment by mthalman** [comment]
Any update here? This will block this week's release.

**Comment by MattGal** [comment]
@mthalman I was away Friday for training, but Thursday I was able to build https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/alpine/3.14/helix/arm32v7/Dockerfile without issue on a DPS_v5 Azure VM.  I'll give it a shot on an old Tegra machine if I can this morning, but without a repro finding a hacky workaround is going to be more difficult.

**Comment by MattGal** [comment]
@mthalman not only can I not repro the problem for the arm Alpine Helix docker thing you asked about on a "real" Tegra in addition to the Azure VM I used, I see green builds of that image in this build https://dev.azure.com/dnceng/internal/_build/results?buildId=2111090&view=logs&j=1bd276f8-9fb5-54c7-5be2-bbe0faefcec6&t=78f2343a-ba72-59a4-e152-58a1d5b13d94.  

Help me understand what I'm missing.  I get that Chad found an issue about similar subjects that was closed two years ago but I feel like we dealt with _that_ problem two years ago.  If you can help me get a repro I'll try to fix it, but seeing the image successfully published to Staging makes me feel like it's not really a problem.

Thanks,
Matt

**Comment by mthalman** [comment]
Closing since this doesn't seem to be affecting the build anymore.
