### ISSUE TITLE
Python failures in some images 

### ISSUE THREAD

**Issue by riarenas** [dotnet/dotnet-buildtools-prereqs-docker#811]
https://dnceng.visualstudio.com/internal/_build/results?buildId=2120517&view=logs&j=7fe7866b-976f-5cfc-8d56-2ef32e396b04&t=866f8158-fb03-5037-52ad-5232cb9d60aa

```
Step 4/7 : RUN ln -sf /usr/bin/python3 /usr/bin/python &&     python -m pip install virtualenv==20.17.1 &&     python -m pip download --no-deps helix-scripts --index-url https://dnceng.pkgs.visualstudio.com/public/_packaging/helix-client-prod/pypi/simple &&     export CRYPTOGRAPHY_DONT_BUILD_RUST=1 &&     python -m pip install ./helix_scripts-*-py3-none-any.whl
 ---> Running in 2cfec2ce76ac
error: externally-managed-environment

× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
    python3-xyz, where xyz is the package you are trying to
    install.
    
    If you wish to install a non-Debian-packaged Python package,
    create a virtual environment using python3 -m venv path/to/venv.
    Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
    sure you have python3-full installed.
    
    If you wish to install a non-Debian packaged Python application,
    it may be easiest to use pipx install xyz, which will manage a
    virtual environment for you. Make sure you have pipx installed.
    
    See /usr/share/doc/python3.11/README.venv for more information.

note: If you believe this is a mistake, please contact your Python installation or OS distribution provider. You can override this, at the risk of breaking your Python installation or OS, by passing --break-system-packages.
hint: See PEP 668 for the detailed specification.
The command '/bin/sh -c ln -sf /usr/bin/python3 /usr/bin/python &&     python -m pip install virtualenv==20.17.1 &&     python -m pip download --no-deps helix-scripts --index-url https://dnceng.pkgs.visualstudio.com/public/_packaging/helix-client-prod/pypi/simple &&     export CRYPTOGRAPHY_DONT_BUILD_RUST=1 &&     python -m pip install ./helix_scripts-*-py3-none-any.whl' returned a non-zero code: 1

-- EXECUTION ELAPSED TIME: 00:14:21.7883635
-- EXECUTING: docker logout dotnetdocker.azurecr.io
Removing login credentials for dotnetdocker.azurecr.io
-- EXECUTION ELAPSED TIME: 00:00:00.0305325
Unhandled exception: System.InvalidOperationException: Failed to execute docker build --platform linux/arm64/v8 -t dotnetdocker.azurecr.io/build-staging/2120517/dotnet-buildtools/prereqs:debian-12-helix-arm64v8-20230222225712-49d60db -t dotnetdocker.azurecr.io/build-staging/2120517/dotnet-buildtools/prereqs:debian-12-helix-arm64v8 -f dotnet-dotnet-buildtools-prereqs-docker/src/debian/12/helix/arm64v8/Dockerfile dotnet-dotnet-buildtools-prereqs-docker/src/debian/12/helix/arm64v8
```

**Comment by mthalman** [comment]
@MattGal - Do you know what the issue might be here or know who we can send Helix issues to?

**Comment by mthalman** [comment]
I've had to disable the [dotnet-buildtools-prereqs-docker-all](https://dev.azure.com/dnceng/internal/_build?definitionId=1183) pipeline (internal Microsoft link) due to this issue. It's attempting to rebuild all Debian images because the base image updated. But the build is failing due to this issue. The pipeline needs to be disabled to avoid having it keep retrying.

**Comment by MichaelSimons** [comment]
@markwilkie - Do you have a suggestion on who we can get to help fix this issue with the Helix Docker images?  TIA

**Comment by markwilkie** [comment]
Is the situation that Python is missing?

**Comment by MattGal** [comment]
> Is the situation that Python is missing?

No, this error indicates that a dependency was installed via a package manager, not pip, and needs to be either avoided or uninstalled as a non-PIP version.

**Comment by markwilkie** [comment]
Thanks Matt!  How has this kind of thing been handled in the past?

**Comment by MattGal** [comment]
Mostly @mthalman  or @MichaelSimons would ping me or make an FR issue and I'd fix it.  

Once you figure out who will do the work, the general process for fixing something is you get yourself a repro (easily done using the dockerfile from the failed build), you change it until it works, then make a PR out of that... there no "fancy" way to debug Dockerfiles but it's a pretty fast iteration loop at least.

**Comment by wfurt** [comment]
This is essentially https://github.com/python/cpython/issues/102134 
I will take a look. Seems to be common issue and the recommendation is to use virtual env ... that we do use anyway.

**Comment by MattGal** [comment]
> This is essentially [python/cpython#102134](https://github.com/python/cpython/issues/102134) I will take a look. Seems to be common issue and the recommendation is to use virtual env ... that we do use anyway.

Helix docker images assume there's an entry point named "python" they can just call and use.  If you can make it so an arbitrary script or command being run in the container runs a virtualenv python by invoking "python", that'd work.

**Comment by wfurt** [comment]
I put up  #819 as quick fix. We may look into it more so we do not need to override the distro.  Since this is closed and limited environment it is probably ok for now.

**Comment by wfurt** [comment]
> Helix docker images assume there's an entry point named "python" they can just call and use. If you can make it so an

Would Helix respect the `PYTHON` env? (or could it easily enough)

**Comment by MattGal** [comment]
> > Helix docker images assume there's an entry point named "python" they can just call and use. If you can make it so an
> 
> Would Helix respect the `PYTHON` env? (or could it easily enough)

Through software, all things are possible.  Unfortunately it has been decided that I don't work on this any more and it would seem inappropriate for me to comment on policy going forward.

**Comment by wfurt** [comment]
fair. I think it can still work instead of the existing symbolic link. Respecting `PYTHON` would simply require less craft.

**Comment by markwilkie** [comment]
> Would Helix respect the PYTHON env? (or could it easily enough)

I'm not opposed

**Comment by wfurt** [comment]
I'm not really sure it is needed. I was mostly asking because I know near nothing about Helix. 
And I was thinking about how one can sneak in with wrapper script of some kind.
https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/819 is merged and it should be sufficient for now IMHO. 

So we can perhaps close this issue and open new one (here or Arcade) for more sustainable fix - as improvement.  

I also noticed
```
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

Perhaps the goal would be to get on Python's recommended best practices.

**Comment by mthalman** [comment]
I'm closing this issue since the failure it describes is resolved. Feel free to log a new issue elsewhere for more improvements.
