### ISSUE TITLE
Delete Fedora 36 Dockerfiles after its EOL date

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#839]
Fedora is scheduled to reach EOL on May 10, 2023 (see https://github.com/dotnet/core/issues/8367).

cc @wfurt

**Comment by lbussell** [comment]
Fedora 36 Dockerfiles were replaced with Fedora 38 in https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/886.
