### ISSUE TITLE
Ubuntu builds failing due to freebsd error

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#855]
The Ubuntu build 18.04 build leg is failing due to this Dockerfile: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/ubuntu/18.04/cross/freebsd/12/Dockerfile. It's prebuild step executes here: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/ubuntu/18.04/cross/freebsd/12/hooks/pre-build. This runs arcade's build-rootfs script targeting freebsd. That implementation is no longer working and causes this error in the build:

```
Running dotnet/arcade's build-rootfs.sh
--2023-04-21 04:46:10--  https://download.freebsd.org/ftp/releases/amd64/amd64/12.3-RELEASE/base.txz
Resolving download.freebsd.org (download.freebsd.org)... 149.20.1.200, 2001:4f8:1:11::15:0
Connecting to download.freebsd.org (download.freebsd.org)|149.20.1.200|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-04-21 04:46:10 ERROR 404: Not Found.

xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
```

**Comment by mthalman** [comment]
@am11 - Can you take a look at this?

**Comment by mthalman** [comment]
And now it's failing for 13.0, which is already [identified as EOL](https://github.com/dotnet/arcade/pull/13247#issuecomment-1518051863). Reopening.

**Comment by am11** [comment]
Yup we were just discussing it: https://github.com/dotnet/arcade/pull/13249

**Comment by mthalman** [comment]
Build is fixed now.
