### ISSUE TITLE
OpenMP support is missing from Centos and Ubuntu images

### ISSUE THREAD

**Issue by singlis** [dotnet/dotnet-buildtools-prereqs-docker#93]
ML.Net (http://github.com/dotnet/machinelearning/) uses the Centos 7 and Ubuntu 16.04 docker images for Linux builds. Recently I added changes that use OpenMP and noticed that both of these containers fail the build due to missing OpenMP support.

This is a request to add LLVM OpenMP support to the Centos and Ubuntu images.

**Comment by MichaelSimons** [comment]
@Th
