### ISSUE TITLE
FreeBSD package archive errors from rootfs script

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#950]
The `Linux_amd64 src-ubuntu-18.04-coredeps-graph` build leg is failing with this error:

```
pkg: http://pkgmir.geo.freebsd.org/FreeBSD:12:amd64/quarterly/meta.txz: Not Found
pkg: http://pkgmir.geo.freebsd.org/FreeBSD:12:amd64/quarterly/packagesite.pkg: Not Found
pkg: http://pkgmir.geo.freebsd.org/FreeBSD:12:amd64/quarterly/packagesite.txz: Not Found
```

This occurs when executing https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/ubuntu/18.04/cross/freebsd/12/hooks/pre-build

This occurs when building with image caching disabled.

[Build link](https://dev.azure.com/dnceng/internal/_build/results?buildId=2350030&view=logs&j=fc59f0f2-c1bd-58ae-b870-833d1e8a924c&t=8d53baa0-ff68-5ea5-041a-af0e08303d7f) (internal only)

**Comment by akoeplinger** [comment]
Looks like FreeBSD 12 is EOL.

**Comment by wfurt** [comment]
cc: @Thefrank @sec @am11 
I guess time to move to 13 or should we jump to 14?

**Comment by am11** [comment]
> If possible, add images for 14-x86_64 (amd64) and 14-aarch64 (arm64).

That would go in https://github.com/dotnet/arcade/blob/main/eng/common/cross/build-rootfs.sh.

> Should we move to 20.04?

Either to Ubuntu 22.04 where we have riscv64 atm, or CBL-mariner where all the other architecture images are going these days. It can be done in a subsequent PR.
