### ISSUE TITLE
npm install error on wasm helix Dockerfile

### ISSUE THREAD

**Issue by mthalman** [dotnet/dotnet-buildtools-prereqs-docker#951]
When image caching is disabled, the `Linux_amd64 src-ubuntu-18.04-helix-graph` build leg is failing with this error:

```
 > [4/7] RUN npm install -g npm:
#7 0.709 npm ERR! code EBADENGINE
#7 0.710 npm ERR! engine Unsupported engine
#7 0.710 npm ERR! engine Not compatible with your version of node/npm: npm@10.2.5
#7 0.710 npm ERR! notsup Not compatible with your version of node/npm: npm@10.2.5
#7 0.711 npm ERR! notsup Required: {"node":"^18.17.0 || >=20.5.0"}
#7 0.711 npm ERR! notsup Actual:   {"npm":"8.19.3","node":"v16.19.0"}
#7 0.712 
#7 0.712 npm ERR! A complete log of this run can be found in:
#7 0.712 npm ERR!     /root/.npm/_logs/2024-01-10T17_06_48_948Z-debug-0.log
```

This happens when building Dockerfile: https://github.com/dotnet/dotnet-buildtools-prereqs-docker/blob/main/src/ubuntu/18.04/helix/webassembly/Dockerfile

[Build link](https://dev.azure.com/dnceng/internal/_build/results?buildId=2350030&view=logs&j=5451b624-d93a-5e9f-b2ab-9f4f54898441&t=2c21da90-b57a-50a1-180d-c2015e5bb13d) (internal only)

**Comment by lbussell** [comment]
[Triage] Looks like @radekdoulik was maintaining this Dockerfile in the past.
