### ISSUE TITLE
State of the production branch

### ISSUE THREAD

**Issue by akoeplinger** [dotnet/dotnet-buildtools-prereqs-docker#956]
@mthalman is the branch still used? I see it was last updated about a year ago.

**Comment by mthalman** [comment]
It's unused right now. It was used while dnceng was managing rollout of these images but they're no longer managing it.

**Comment by akoeplinger** [comment]
Ok. do you think there is value in keeping it or should we remove it to reduce confusion like in https://github.com/dotnet/runtime/pull/96827#issuecomment-1887739678?

**Comment by mthalman** [comment]
We'll discuss it next week in triage to determine the action to take here. Thanks for bringing this up.

**Comment by lbussell** [comment]
[Triage] We'll delete this production branch and the [image-info file](https://github.com/dotnet/versions/blob/main/build-info/docker/image-info.dotnet-dotnet-buildtools-prereqs-docker-production.json).

**Comment by lbussell** [comment]
I removed the production branch this morning so this issue is resolved.
