### ISSUE TITLE
Document process for unblocking builds / maintaining this repo

### ISSUE THREAD

**Issue by lbussell** [dotnet/dotnet-buildtools-prereqs-docker#972]
We should document the current process we follow in order to maintain this repo so that we can analyze it and make specific process improvements in the future.

This process is, in general:

1. Check if builds are failing.
2. If automatic image rebuilds are blocked due to image build failure, log an issue and delete/disable the Dockerfile that is failing to build.
3. Contact repo owners that contribute most to the failing Dockerfiles and ask them to fix it.

We should consider also updating the process to include:

- A CODEOWNERS file so that we know which product teams specifically own each Dockerfile
- ... I am open to suggestions for other process improvements that we can implement right now.

**Comment by MichaelSimons** [comment]
This policy should also include the expectations around mitigating s360 reported vulnerabilities.
