### ISSUE TITLE
Upcoming CentOS Stream 8 EOL on May 31st, 2024 

### ISSUE THREAD

**Issue by omajid** [dotnet/dotnet-buildtools-prereqs-docker#973]
We use CentOS Stream 8 container images in this repo. They are going EOL on  May 31st, 2024: https://blog.centos.org/2023/04/end-dates-are-coming-for-centos-stream-8-and-centos-linux-7/

**Comment by lbussell** [comment]
[Triage] @epananth here's a good example to look at for defining the workflow for this repo. The CentOS Stream 8 image is the default image in Arcade for source-build legs in product repos: https://github.com/dotnet/arcade/blob/main/eng/common/templates/jobs/source-build.yml#L15

Ideally, the report would flag this EOL date some number of months and there should be some automated tooling to allow us to open issues against product repos to update to a newer (in support) OS image.
